import type { Board } from "@/lib/types";

export const seedBoard: Board = {
  professors: [
    {
      id: 1,
      fullTitle: "Mtra. Roxana Trigueros Olivares",
      area: "Histórico",
      office: "Edificio D · cubículo 12",
      hours: "Lun y mié 14:15–15:15",
      modality: "Presencial",
    },
    {
      id: 2,
      fullTitle: "Lic. Arturo Belmont Martínez",
      area: "Civil",
      office: "Edificio D · cubículo 08",
      hours: "Mar y jue 14:15–15:15",
      modality: "Presencial",
    },
    {
      id: 3,
      fullTitle: "Lic. Dionisio Eduardo Barco Martínez",
      area: "Histórico",
      office: "Edificio D · cubículo 18",
      hours: "Vie 14:15–15:30",
      modality: "Presencial",
    },
    {
      id: 4,
      fullTitle: "Dr. Marcial Manuel Cruz Vázquez",
      area: "Público",
      office: "Edificio E · cubículo 04",
      hours: "Lun 15:30–16:30",
      modality: "Presencial",
    },
    {
      id: 5,
      fullTitle: "Mtra. María Fernanda González Nahle",
      area: "Social",
      office: "Edificio D · cubículo 21",
      hours: "Mié 15:30–16:30",
      modality: "Presencial",
    },
    {
      id: 6,
      fullTitle: "Mtra. Lizzet Urbina Anguas",
      area: "Fundamentos",
      office: "Edificio D · cubículo 05",
      hours: "Jue 15:30–16:30",
      modality: "Presencial",
    },
    {
      id: 7,
      fullTitle: "Lic. Apolinar Medardo Ramírez Figueroa",
      area: "Formación",
      office: "Edificio E · cubículo 11",
      hours: "Vie 15:30–16:15",
      modality: "Presencial",
    },
  ],
  courses: [
    {
      id: 1,
      code: "1122",
      name: "Derecho romano I",
      chair: "Mtra. Roxana Trigueros Olivares",
      modality: "Presencial",
      weekday: "Lunes a viernes",
      timeSlot: "07:00–08:00",
      place: "D-106",
      semester: "Primer semestre",
      group: "9114",
    },
    {
      id: 2,
      code: "1121",
      name: "Acto jurídico y derecho de las personas",
      chair: "Lic. Arturo Belmont Martínez",
      modality: "Presencial",
      weekday: "Lunes a viernes",
      timeSlot: "08:00–09:00",
      place: "D-106",
      semester: "Primer semestre",
      group: "9114",
    },
    {
      id: 3,
      code: "1123",
      name: "Historia del derecho mexicano",
      chair: "Lic. Dionisio Eduardo Barco Martínez",
      modality: "Presencial",
      weekday: "Lunes a viernes",
      timeSlot: "09:00–10:00",
      place: "D-106",
      semester: "Primer semestre",
      group: "9114",
    },
    {
      id: 4,
      code: "1127",
      name: "Teoría general del Estado",
      chair: "Dr. Marcial Manuel Cruz Vázquez",
      modality: "Presencial",
      weekday: "Lunes a viernes",
      timeSlot: "10:00–11:00",
      place: "D-106",
      semester: "Primer semestre",
      group: "9114",
    },
    {
      id: 5,
      code: "1126",
      name: "Sociología jurídica",
      chair: "Mtra. María Fernanda González Nahle",
      modality: "Presencial",
      weekday: "Lunes a viernes",
      timeSlot: "11:00–12:00",
      place: "D-106",
      semester: "Primer semestre",
      group: "9114",
    },
    {
      id: 6,
      code: "1124",
      name: "Introducción a la teoría del derecho",
      chair: "Mtra. Lizzet Urbina Anguas",
      modality: "Presencial",
      weekday: "Lunes a viernes",
      timeSlot: "12:00–13:00",
      place: "D-106",
      semester: "Primer semestre",
      group: "9114",
    },
    {
      id: 7,
      code: "1125",
      name: "Ser universitario y cultura de la legalidad",
      chair: "Lic. Apolinar Medardo Ramírez Figueroa",
      modality: "Presencial",
      weekday: "Lunes a viernes",
      timeSlot: "13:00–14:00",
      place: "E-003",
      semester: "Primer semestre",
      group: "9114",
    },
  ],
  events: [
    {
      id: 1,
      title: "Lectura de instituciones de Gayo",
      kind: "Taller",
      eventDate: "2026-09-08",
      timeSlot: "16:00–17:30",
      place: "Biblioteca · mesa 2",
      modality: "Presencial",
      description: "Derecho romano I. Ficha de una cuartilla sobre personas y cosas.",
      hostAlias: "Mesa 9114",
    },
    {
      id: 2,
      title: "Mapa de elementos del acto jurídico",
      kind: "Taller",
      eventDate: "2026-09-10",
      timeSlot: "16:00–17:30",
      place: "D-106",
      modality: "Presencial",
      description: "Consentimiento, objeto y solemnidad. Traer el código civil anotado.",
      hostAlias: "Mesa civil",
    },
    {
      id: 3,
      title: "Línea del tiempo del derecho novohispano",
      kind: "Actividad",
      eventDate: "2026-09-11",
      timeSlot: "16:00–18:00",
      place: "Jardín del edificio D",
      modality: "Presencial",
      description: "Historia del derecho mexicano. Cada equipo cubre un siglo.",
      hostAlias: "Mesa histórica",
    },
    {
      id: 4,
      title: "Cineforo: cultura de la legalidad",
      kind: "Actividad",
      eventDate: "2026-09-12",
      timeSlot: "16:30–18:30",
      place: "E-003",
      modality: "Presencial",
      description: "Proyección corta y mesa de Ser universitario. Cupo del grupo 9114.",
      hostAlias: "Grupo 9114",
    },
    {
      id: 5,
      title: "Seminario: Estado, soberanía y constitución",
      kind: "Conferencia",
      eventDate: "2026-09-15",
      timeSlot: "16:00–18:00",
      place: "Aula virtual 1",
      modality: "En línea",
      description: "Teoría general del Estado. Preguntas al final, una por mesa.",
      hostAlias: "Cátedra de TGE",
    },
    {
      id: 6,
      title: "Observación de campo para sociología jurídica",
      kind: "Taller",
      eventDate: "2026-09-17",
      timeSlot: "16:00–18:00",
      place: "Patio central",
      modality: "Presencial",
      description: "Registro de normas vividas en el campus. Entrega de nota el viernes.",
      hostAlias: "Mesa sociología",
    },
  ],
  books: [
    {
      id: 1,
      title: "Instituciones de Justiniano",
      author: "Trad. García del Corral",
      kind: "Préstamo",
      course: "Derecho romano I",
      notes: "Casillero D-106. Devolución el lunes siguiente.",
      ownerAlias: "Mesa romana",
    },
    {
      id: 2,
      title: "Derecho civil. Personas",
      author: "Rojina Villegas",
      kind: "Venta",
      course: "Acto jurídico y personas",
      notes: "Usado, poco subrayado. Precio a convenir en el mural.",
      ownerAlias: "Estantería 9114",
    },
    {
      id: 3,
      title: "Historia del derecho mexicano",
      author: "Guillermo Floris Margadant",
      kind: "Préstamo",
      course: "Historia del derecho mexicano",
      notes: "Hay dos ejemplares. Recoger en D-106 al terminar la hora.",
      ownerAlias: "Mesa histórica",
    },
    {
      id: 4,
      title: "Teoría general del Estado",
      author: "Jellinek / García Pelayo",
      kind: "Recomendación",
      course: "Teoría general del Estado",
      notes: "Empieza por el capítulo de soberanía. Hay fotocopias en E-003.",
      ownerAlias: "Mesa pública",
    },
    {
      id: 5,
      title: "Sociología jurídica",
      author: "Elías Díaz / Treves",
      kind: "Recomendación",
      course: "Sociología jurídica",
      notes: "Lectura corta para el taller de campo.",
      ownerAlias: "Mesa sociología",
    },
    {
      id: 6,
      title: "Introducción al estudio del derecho",
      author: "García Máynez",
      kind: "Venta",
      course: "Introducción a la teoría del derecho",
      notes: "Pasta suave. Dejar recado en el casillero del grupo.",
      ownerAlias: "Estantería 9114",
    },
    {
      id: 7,
      title: "Ética y cultura de la legalidad",
      author: "Material de la cátedra",
      kind: "Préstamo",
      course: "Ser universitario y cultura de la legalidad",
      notes: "Cuadernillo de la materia. Se queda en E-003.",
      ownerAlias: "Grupo 9114",
    },
  ],
  rides: [
    {
      id: 1,
      direction: "Ida",
      fromPlace: "Parada principal",
      toPlace: "Edificio D · D-106",
      weekday: "Lunes",
      timeSlot: "06:35",
      seats: 3,
      notes: "Para llegar a Romano a las 07:00. Punto: banqueta oriente.",
      ownerAlias: "Ruta 9114",
      reservations: [],
    },
    {
      id: 2,
      direction: "Ida",
      fromPlace: "Parada principal",
      toPlace: "Edificio D · D-106",
      weekday: "Martes",
      timeSlot: "06:35",
      seats: 3,
      notes: "Misma ruta. Avisar la noche anterior en el mural.",
      ownerAlias: "Ruta 9114",
      reservations: [],
    },
    {
      id: 3,
      direction: "Vuelta",
      fromPlace: "Edificio E · E-003",
      toPlace: "Parada principal",
      weekday: "Lunes",
      timeSlot: "14:10",
      seats: 4,
      notes: "Sale al terminar Ser universitario.",
      ownerAlias: "Ruta 9114",
      reservations: [],
    },
    {
      id: 4,
      direction: "Vuelta",
      fromPlace: "Edificio E · E-003",
      toPlace: "Parada principal",
      weekday: "Miércoles",
      timeSlot: "14:10",
      seats: 3,
      notes: "Una parada en la biblioteca si hay quien baje.",
      ownerAlias: "Ruta 9114",
      reservations: [],
    },
    {
      id: 5,
      direction: "Ida",
      fromPlace: "Parada norte",
      toPlace: "Edificio D · D-106",
      weekday: "Viernes",
      timeSlot: "06:40",
      seats: 2,
      notes: "Solo viernes. Llegar con diez minutos.",
      ownerAlias: "Ruta norte",
      reservations: [],
    },
  ],
  groups: [
    {
      id: 1,
      name: "Mesa romana",
      course: "Derecho romano I",
      whenText: "Lunes 16:00",
      place: "Biblioteca · mesa 2",
      notes: "Una institución por semana. Ficha de una cuartilla.",
    },
    {
      id: 2,
      name: "Mesa de personas",
      course: "Acto jurídico y derecho de las personas",
      whenText: "Martes 16:00",
      place: "D-106",
      notes: "Casos de capacidad y nulidad. Código a la mano.",
    },
    {
      id: 3,
      name: "Mesa histórica",
      course: "Historia del derecho mexicano",
      whenText: "Jueves 16:00",
      place: "Cafetería D",
      notes: "Un periodo por sesión. Línea del tiempo compartida.",
    },
    {
      id: 4,
      name: "Mesa de teoría",
      course: "Introducción a la teoría del derecho",
      whenText: "Sábado 10:00",
      place: "En línea · aula 7",
      notes: "Norma, validez y fuentes. Un esquema por domingo.",
    },
    {
      id: 5,
      name: "Círculo de sociología",
      course: "Sociología jurídica",
      whenText: "Miércoles 16:00",
      place: "Patio central",
      notes: "Notas de campo. Máximo ocho personas.",
    },
  ],
  notices: [
    {
      id: 1,
      title: "Jornada del grupo 9114",
      body: "Siete horas seguidas: 07:00 a 14:00. Seis materias en D-106; Ser universitario pasa a E-003 a las 13:00.",
      pinned: true,
      createdAt: "2026-09-04T10:00:00.000Z",
    },
    {
      id: 2,
      title: "Cambio de salón a las 13:00",
      body: "Al terminar Teoría del derecho hay que cruzar al edificio E. Dejar mochilas listas a las 12:50.",
      pinned: true,
      createdAt: "2026-09-04T12:00:00.000Z",
    },
    {
      id: 3,
      title: "Lista de asistencia en D-106",
      body: "Pasa al inicio de Romano. Quien llegue después de las 07:10 firma al final.",
      pinned: false,
      createdAt: "2026-09-03T18:00:00.000Z",
    },
    {
      id: 4,
      title: "Fotocopias de García Máynez",
      body: "Hay un tanto en el casillero del grupo, junto al pizarrón de D-106.",
      pinned: false,
      createdAt: "2026-09-03T09:00:00.000Z",
    },
  ],
  posts: [
    {
      id: 1,
      title: "Primera jornada del grupo 9114",
      body: "Arranque de clases en D-106. Bitácora abierta para compartir fotos, acuerdos y evidencias de actividades.",
      imageUrl: null,
      imageName: null,
      shotDate: "2026-09-04",
      place: "D-106",
      authorAlias: "Moderación 9114",
      createdAt: "2026-09-04T08:30:00.000Z",
    },
    {
      id: 2,
      title: "Cruce a E-003",
      body: "Última materia del bloque diario. Aquí podrán subir fotos del cambio de edificio y avisos rápidos del grupo.",
      imageUrl: null,
      imageName: null,
      shotDate: "2026-09-04",
      place: "E-003",
      authorAlias: "Grupo 9114",
      createdAt: "2026-09-04T13:05:00.000Z",
    },
  ],
  materials: [],
  services: [],
};
