import test from 'node:test';import assert from 'node:assert/strict';
import { selectNews,homeNews } from '../../src/lib/news/selection.ts';
import { parseOfficialHtmlV72 } from '../../src/lib/news/parser-v72.ts';
import { DEFAULT_NEWS_SOURCES,mergeSettings } from '../../src/lib/news/sources.ts';
import { nextCourse,campusClock,upcomingEvents } from '../../src/lib/home-view.ts';
import type {NewsItem} from '../../src/lib/news/types.ts';
import type {Course,EventItem} from '../../src/lib/types.ts';
const now=Date.parse('2026-10-07T12:00:00Z');
const item=(id:string,date:string|null,source='gaceta'):NewsItem=>({id,title:`Titular académico original ${id}`,summary:'Extracto de prueba',sourceId:source,sourceName:source,sourceUrl:`https://www.gaceta.unam.mx/${id}/`,category:'Facultad',legalStage:'Información',publishedAt:date,eventDate:null});
const rows=[item('reciente','2026-10-05T12:00:00Z'),item('antiguo','2022-01-01T12:00:00Z'),item('sin-fecha',null)];
test('Noticias abre todas las fechas sin ocultar archivo ni avisos sin fecha',()=>assert.equal(selectNews(rows,{now}).length,3));
test('Filtro reciente excluye lo antiguo y no fabrica fechas de avisos',()=>{assert.deepEqual(selectNews(rows,{now,period:'recientes'}).map(i=>i.id),['reciente']);assert.equal(rows[2].publishedAt,null);});
test('Filtro sin fecha distingue desconocido de reciente',()=>assert.deepEqual(selectNews(rows,{period:'sin-fecha'}).map(i=>i.id),['sin-fecha']));
test('Filtros fuente y guardados no alteran registros',()=>assert.deepEqual(selectNews(rows,{source:'gaceta',saved:['antiguo']}).map(i=>i.id),['antiguo']));
test('Inicio combina fuentes sin inventar titulares ni duplicarlos',()=>{const chosen=homeNews([item('a','2026-10-06'),item('b','2026-10-05'),item('c','2026-10-04','dua'),item('d','2026-10-03','dof')]);assert.equal(chosen.length,3);assert.equal(new Set(chosen.map(i=>i.sourceId)).size,3);});
test('Inicio vacío permanece vacío',()=>assert.equal(homeNews([]).length,0));
const source=DEFAULT_NEWS_SOURCES.find(s=>s.id==='gaceta')!;
test('Lector complementa encabezados con enlaces de otras tarjetas',()=>{const out=parseOfficialHtmlV72('<h3><a href="/primera/">Primera conferencia sobre los derechos humanos</a></h3><a href="/segunda/">Segunda conferencia sobre el derecho ambiental</a>',source);assert.equal(out.length,2);});
test('Un cartel enlazado obtiene título e imagen propios, sin inventar fecha',()=>{const out=parseOfficialHtmlV72('<a href="/convocatoria/"><img alt="Convocatoria al seminario sobre derecho ambiental" src="/cartel.jpg"></a>',source);assert.equal(out.length,1);assert.ok(out[0].imageUrl?.endsWith('/cartel.jpg'));assert.equal(out[0].publishedAt,null);});
test('Lector rechaza enlaces externos y navegación de categorías',()=>{assert.throws(()=>parseOfficialHtmlV72('<a href="https://evil.example/nota/">Conferencia sobre el derecho de las personas</a><a href="/tag/derecho/">Conferencia sobre el derecho de las personas</a>',source));});
test('El Búho sólo incorpora enlaces a artículos',()=>{const buho=DEFAULT_NEWS_SOURCES.find(s=>s.id==='buho')!;const out=parseOfficialHtmlV72('<h3><a href="/index.php/derecho/issue/current">Número actual de la publicación</a></h3><a href="/index.php/derecho/article/view/123">Un ensayo sobre las normas jurídicas</a>',buho);assert.equal(out.length,1);assert.ok(out[0].sourceUrl.includes('/article/view/'));});
test('Nuevas fuentes preservan desactivación de las anteriores',()=>{const value=mergeSettings({sources:[{...source,enabled:false}]});assert.equal(value.sources.find(s=>s.id==='gaceta')?.enabled,false);assert.equal(value.sources.find(s=>s.id==='gaceta-actualidad')?.enabled,true);});
const course=(day:string,time:string):Course=>({id:1,code:'x',name:'Materia de prueba',chair:'Docente',modality:'Presencial',weekday:day,timeSlot:time,place:'Aula',semester:'1',group:'9114'});
test('Reloj de campus no confunde UTC con la fecha de México',()=>assert.equal(campusClock(Date.parse('2026-10-07T02:00:00Z')).date,'2026-10-06'));
test('Próxima clase reconoce acentos y hora futura del mismo día',()=>assert.equal(nextCourse([course('Miércoles','09:00–11:00')],now)?.date,'2026-10-07'));
test('Clase ya iniciada se desplaza a la semana siguiente',()=>assert.equal(nextCourse([course('Miércoles','05:00–07:00')],now)?.date,'2026-10-14'));
test('Horarios indeterminados no generan una próxima clase ficticia',()=>assert.equal(nextCourse([course('Por definir','Pendiente')],now),null));
test('Agenda excluye fechas pasadas e inválidas',()=>{const events=['2026-10-01','2026-10-08','2026-02-30'].map((date,i)=>({id:i,eventDate:date,timeSlot:'09:00'} as EventItem));assert.deepEqual(upcomingEvents(events,'2026-10-07').map(e=>e.eventDate),['2026-10-08']);});
