import { createFileRoute } from "@tanstack/react-router";
import { Pencil, X } from "lucide-react";
import { useMemo, useState, type FormEvent } from "react";
import { Shell } from "@/components/shell";
import { useBoard, useRefreshBoard } from "@/components/board-context";
import { Button, Card, Field, FormBox, Input, Pill, Select, Textarea } from "@/components/ui";
import { PublishGate } from "@/components/publish-gate";
import { canEditPublication, useAreaVisit, useDirectory } from "@/components/directory";
import { addEvent, updateEvent } from "@/lib/content";
import { formatLongDate, getTodayIso } from "@/lib/format";
import type { EventItem } from "@/lib/types";

export const Route = createFileRoute("/agenda")({ component: AgendaPage });
const KINDS = ["Todas", "Taller", "Conferencia", "Actividad", "Clínica", "Social"] as const;

function AgendaPage() {
  const { events } = useBoard(); const refresh = useRefreshBoard(); const { user, directory } = useDirectory(); useAreaVisit("agenda");
  const [filter, setFilter] = useState<(typeof KINDS)[number]>("Todas"); const [error, setError] = useState<string | null>(null); const [success, setSuccess] = useState<string | null>(null); const [editing, setEditing] = useState<EventItem | null>(null);
  const visible = useMemo(() => events.filter((event) => filter === "Todas" || event.kind === filter), [events, filter]);
  function read(data: FormData) { return { title: String(data.get("title") ?? "").trim(), kind: String(data.get("kind") ?? "Taller") as "Taller", eventDate: String(data.get("eventDate") ?? ""), timeSlot: String(data.get("timeSlot") ?? "").trim(), place: String(data.get("place") ?? "").trim(), modality: String(data.get("modality") ?? "Presencial") as "Presencial", description: String(data.get("description") ?? "").trim(), hostAlias: String(data.get("hostAlias") ?? "").trim() }; }
  async function onSubmit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(null); setSuccess(null); const form=event.currentTarget; const data=read(new FormData(form)); try { await addEvent({data}); form.reset(); setSuccess("Actividad publicada en la agenda."); await refresh(); } catch { setError("Entra al padrón para publicar. Revisa los campos."); } }
  async function onEdit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if(!editing)return; setError(null); const data=read(new FormData(event.currentTarget)); try { await updateEvent({data:{id:editing.id,...data}}); setEditing(null); setSuccess("Actividad actualizada."); await refresh(); } catch(cause){ const m=cause instanceof Error?cause.message:"No se pudo guardar."; setError(/autor de la publicación|administrador/i.test(m)?"Sólo el autor o un administrador puede editar esta actividad.":m); } }
  return <Shell eyebrow="Después de las 14:00" title="Talleres del grupo, cuando suelta E-003." lead="Lecturas de romano, mapas del acto jurídico y cineforo de legalidad. Publica con el alias de tu mesa.">
    <div className="mb-6 flex flex-wrap gap-2">{KINDS.map((item)=><button key={item} type="button" onClick={()=>setFilter(item)} aria-pressed={filter===item} className={filter===item?"min-h-11 rounded-full bg-forest px-4 text-sm text-bg":"min-h-11 rounded-full border border-line bg-surface px-4 text-sm text-ink-soft"}>{item}</button>)}</div>
    <div className="grid gap-6 lg:grid-cols-3"><div className="grid gap-4 lg:col-span-2">{visible.map((item)=>{const editable=canEditPublication(directory,user?.id,item.createdBy);return <Card key={item.id}><div className="flex flex-wrap items-center justify-between gap-2"><div className="flex flex-wrap items-center gap-2"><Pill>{item.kind}</Pill><Pill>{item.modality}</Pill><span className="text-xs tabular-nums text-muted">{formatLongDate(item.eventDate)}</span></div>{editable?<button type="button" onClick={()=>setEditing(item)} className="inline-flex items-center gap-1 rounded-md border border-line bg-white px-2.5 py-1.5 text-xs font-semibold text-forest"><Pencil className="size-3.5"/>Editar</button>:null}</div><h2 className="mt-3 font-display text-2xl">{item.title}</h2><p className="mt-2 text-sm text-muted">{item.description}</p><p className="mt-3 text-sm">{item.timeSlot} · {item.place} · {item.hostAlias}</p></Card>;})}</div><div>{editing?<FormBox title="Editar actividad" onSubmit={onEdit}><Cancel onClick={()=>setEditing(null)}/><EventFields item={editing}/>{error?<p className="text-sm text-danger">{error}</p>:null}<Button type="submit"><Pencil className="mr-2 size-4"/>Guardar cambios</Button></FormBox>:<PublishGate area="agenda"><FormBox title="Publicar en la agenda" onSubmit={onSubmit}><EventFields/>{error?<p className="text-sm text-danger">{error}</p>:null}{success?<p className="rounded-md bg-forest-soft px-3 py-2 text-sm font-medium text-forest-deep">{success}</p>:null}<Button type="submit">Publicar</Button></FormBox></PublishGate>}</div></div>
  </Shell>;
}
function Cancel({onClick}:{onClick:()=>void}){return <div className="flex justify-end"><button type="button" onClick={onClick} className="inline-flex items-center gap-1 text-xs font-semibold text-forest"><X className="size-3.5"/>Cancelar</button></div>}
function EventFields({item}:{item?:EventItem}){return <><Field label="Título"><Input name="title" required maxLength={80} defaultValue={item?.title??""} placeholder="Taller de alegatos"/></Field><Field label="Tipo"><Select name="kind" defaultValue={item?.kind??"Taller"}><option>Taller</option><option>Conferencia</option><option>Actividad</option><option>Clínica</option><option>Social</option></Select></Field><Field label="Fecha"><Input name="eventDate" type="date" required defaultValue={item?.eventDate??getTodayIso()}/></Field><Field label="Horario"><Input name="timeSlot" required defaultValue={item?.timeSlot??""} placeholder="17:00–19:00"/></Field><Field label="Lugar"><Input name="place" required defaultValue={item?.place??""} placeholder="Sala 2 o aula virtual"/></Field><Field label="Modalidad"><Select name="modality" defaultValue={item?.modality??"Presencial"}><option>Presencial</option><option>En línea</option><option>Híbrido</option></Select></Field><Field label="Nota"><Textarea name="description" required maxLength={240} defaultValue={item?.description??""} placeholder="Qué llevar y cupo"/></Field><Field label="Alias de mesa"><Input name="hostAlias" required maxLength={40} defaultValue={item?.hostAlias??""} placeholder="Moot court"/></Field></>}
