import { createFileRoute, Link } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { ArrowRight, ArrowUpRight, BookOpen, CalendarDays, ClipboardCheck, GraduationCap, Headphones, Cloud, Users } from "lucide-react";
import { Shell } from "@/components/shell";
import { NewsSection } from "@/components/news";
import { useBoard,useBoardStatus } from "@/components/board-context";
import { useCurrentUserState } from "@/lib/auth/use-current-user";
import { loadStudyProgress } from "@/lib/study/functions";
import { summarizeProgress } from "@/lib/study/progress";
import { CreditRing } from "@/components/credit-ring";
export const Route=createFileRoute("/")({component:Home});
function Home(){const{user}=useCurrentUserState();const progress=useQuery({queryKey:["study-progress",user?.id],queryFn:()=>loadStudyProgress(),enabled:!!user,retry:1});const summary=summarizeProgress(progress.data?.progress??{});
 return <Shell eyebrow="UNIVERSIDAD ABIERTA · GRUPO 9114" title="Tu comunidad. Tu próximo paso." lead="Un espacio para aprender, organizar el semestre y mantenerte cerca de lo que pasa en Derecho.">
  <section className="fd-hero"><div className="fd-hero-main"><span className="fd-hero-tag"><span/> APRENDER TAMBIÉN ES COMPARTIR</span><h2>El Derecho se estudia.<br/><em>La comunidad se construye.</em></h2><p>De la primera clase al último semestre: tus materiales, el plan completo y la actualidad jurídica, en un mismo lugar.</p><div className="fd-hero-actions"><Link to="/plan-estudios" className="fd-hero-button">Explorar mi carrera <ArrowRight size={17}/></Link><Link to={user?"/catedras":"/login"} className="fd-hero-secondary">{user?"Mis cátedras":"Entrar a la comunidad"} <ArrowUpRight size={17}/></Link></div><div className="fd-hero-baseline"><span>PLAN 2125</span><i/><span>10 SEMESTRES</span><i/><span>450 CRÉDITOS</span></div></div><div className="fd-hero-progress"><p>MI RUTA ACADÉMICA</p><CreditRing credits={summary.credits}/><h3>{user&&progress.data?`${summary.credits} créditos registrados`:"Tu camino empieza aquí"}</h3><span>{user?"Avance personal, no historial oficial":"Inicia sesión para guardar tu avance"}</span><Link to="/plan-estudios">Ver el plan completo <ArrowUpRight size={15}/></Link></div></section>
  <div className="fd-shortcuts">{([{to:"/clases",label:"Mi horario",detail:"Organiza tus clases",icon:CalendarDays},{to:"/catedras",label:"Cátedras",detail:"Apuntes, audio y material",icon:Headphones},{to:"/tareas",label:"Tareas",detail:"Entregas a la vista",icon:ClipboardCheck},{to:"/biblioteca",label:"Biblioteca",detail:"Tu espacio de consulta",icon:BookOpen}] as const).map(({to,label,detail,icon:Icon})=><Link key={to} to={to} className="fd-shortcut"><span><Icon size={22} strokeWidth={1.7}/></span><div><strong>{label}</strong><small>{detail}</small></div><ArrowUpRight size={16}/></Link>)}</div>
  <NewsSection/>
  <div className="fd-home-lower"><section className="fd-academic-callout"><span className="fd-soft-icon"><GraduationCap size={25}/></span><p className="fd-eyebrow">DE PRIMERO A DÉCIMO</p><h2>No pierdas de vista<br/>el camino completo.</h2><p>Consulta las 51 materias obligatorias, explora el catálogo de optativas y conoce los requisitos de inscripción.</p><Link to="/plan-estudios" className="fd-text-link">Abrir plan de estudios <ArrowRight size={16}/></Link><div className="fd-mini-timeline">{Array.from({length:10},(_,i)=><span key={i}>{String(i+1).padStart(2,"0")}</span>)}</div></section><section className="fd-group-panel"><div className="fd-section-heading"><h2>En nuestra comunidad</h2><Users size={22}/></div>{user?<GroupActivity/>:<div className="fd-guest-message"><div className="fd-group-mark">9114</div><h3>El grupo también está aquí.</h3><p>Entra para consultar el material privado, las actividades y las publicaciones de tus compañeros.</p><Link to="/login" search={{mode:"alta"}} className="fd-primary-button">Crear mi cuenta <ArrowUpRight size={16}/></Link></div>}</section></div>
  <div className="fd-storage-note"><Cloud size={20}/><p><strong>Archivos organizados en Google Drive.</strong> Las nuevas cargas utilizan la carpeta autorizada por administración. Si falta la conexión, se informa el error y no se desvía el archivo a otro proveedor.</p><Link to="/control">Configuración <ArrowUpRight size={15}/></Link></div>
 </Shell>;
}
function GroupActivity(){const board=useBoard();const state=useBoardStatus();const items=[...board.materials.slice(0,2).map(m=>({id:`m${m.id}`,title:m.title,meta:m.courseName,to:"/catedras" as const})),...board.tasks.slice(0,2).map(t=>({id:`t${t.id}`,title:t.title,meta:`Entrega: ${t.dueDate}`,to:"/tareas" as const})),...board.notices.slice(0,1).map(n=>({id:`n${n.id}`,title:n.title,meta:"Mural del grupo",to:"/mural" as const}))];if(state.isError)return <p className="fd-alert">No se pudo consultar la actividad privada. Inicia sesión con un registro activo o vuelve a intentarlo.</p>;if(state.isFetching&&!items.length)return <p className="fd-muted">Consultando actividad…</p>;return items.length?<div className="fd-activity-list">{items.map(i=><Link to={i.to} key={i.id}><span><ClipboardCheck size={17}/></span><div><h3>{i.title}</h3><p>{i.meta}</p></div><ArrowUpRight size={16}/></Link>)}</div>:<div className="fd-empty"><BookOpen size={28}/><h3>Todavía no hay publicaciones</h3><p>Las tareas, apuntes y avisos aparecerán aquí cuando el grupo los comparta.</p></div>;}
