import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, ArrowUpRight, BookOpen, CalendarDays, ClipboardCheck, GraduationCap, Headphones, Cloud, Users } from "lucide-react";
import { Shell } from "@/components/shell";
import { NewsSection } from "@/components/news";
import { HomeDashboard, UpcomingEvents } from "@/components/home-dashboard";
import { useBoard, useBoardStatus } from "@/components/board-context";
import { useCurrentUserState } from "@/lib/auth/use-current-user";
export const Route=createFileRoute("/")({component:Home});
function Home(){const{user}=useCurrentUserState();return <Shell eyebrow="UNIVERSIDAD ABIERTA · GRUPO 9114" title="Un portal para ti." lead="Un espacio para aprender, organizar tu semestre y mantenerte cerca de lo que pasa en la Facultad de Derecho.">
 <div className="fd-campus-shortcuts">{([{to:"/plan-estudios",label:"Plan de estudios",detail:"Tu avance académico",icon:GraduationCap},{to:"/clases",label:"Horarios",detail:"Organiza tus clases",icon:CalendarDays},{to:"/catedras",label:"Cátedras",detail:"Apuntes y material",icon:Headphones},{to:"/tareas",label:"Tareas",detail:"Entregas pendientes",icon:ClipboardCheck},{to:"/biblioteca",label:"Biblioteca",detail:"Libros y recursos",icon:BookOpen},{to:"/agenda",label:"Agenda",detail:"Eventos y actividades",icon:CalendarDays}] as const).map(({to,label,detail,icon:Icon})=><Link key={to} to={to}><Icon size={29} strokeWidth={1.6}/><strong>{label}</strong><small>{detail}</small></Link>)}</div>
 <HomeDashboard/>
 <div className="fd-news-and-agenda"><div className="fd-home-news"><NewsSection/></div><UpcomingEvents/></div>
 <div className="fd-home-lower"><section className="fd-academic-callout"><span className="fd-soft-icon"><GraduationCap size={25}/></span><p className="fd-eyebrow">DE PRIMERO A DÉCIMO</p><h2>Tu futuro en Derecho<br/>comienza hoy.</h2><p>Con disciplina, estudio y comunidad. Consulta tus materias y construye tu ruta académica, paso a paso.</p><Link to="/plan-estudios" className="fd-text-link">Explora tu plan de estudios <ArrowRight size={16}/></Link><div className="fd-mini-timeline">{Array.from({length:10},(_,i)=><span key={i}>{String(i+1).padStart(2,"0")}</span>)}</div></section><section className="fd-group-panel"><div className="fd-section-heading"><h2>En nuestra comunidad</h2><Users size={22}/></div>{user?<GroupActivity/>:<div className="fd-guest-message"><h3>El grupo también está aquí.</h3><p>Entra para consultar los materiales, actividades y publicaciones de tus compañeros.</p><Link to="/login" search={{mode:"alta"}} className="fd-primary-button">Crear mi cuenta <ArrowUpRight size={16}/></Link></div>}</section></div>
 <div className="fd-storage-note"><Cloud size={20}/><p><strong>Almacenamiento en Google Drive.</strong> Las cargas requieren una carpeta autorizada. Revisa la conexión en Control antes de subir archivos.</p><Link to="/control">Configuración <ArrowUpRight size={15}/></Link></div>
 </Shell>;}
function GroupActivity(){const board=useBoard();const state=useBoardStatus();const items=[...board.materials.slice(0,2).map(m=>({id:`m${m.id}`,title:m.title,meta:m.courseName,to:"/catedras" as const})),...board.tasks.slice(0,2).map(t=>({id:`t${t.id}`,title:t.title,meta:`Entrega: ${t.dueDate}`,to:"/tareas" as const})),...board.notices.slice(0,1).map(n=>({id:`n${n.id}`,title:n.title,meta:"Mural del grupo",to:"/mural" as const}))];if(state.isError)return <p className="fd-alert">No se pudo consultar la actividad privada. Inicia sesión con un registro activo o vuelve a intentarlo.</p>;if(state.isFetching&&!items.length)return <p className="fd-muted">Consultando actividad…</p>;return items.length?<div className="fd-activity-list">{items.map(i=><Link to={i.to} key={i.id}><span><ClipboardCheck size={17}/></span><div><h3>{i.title}</h3><p>{i.meta}</p></div><ArrowUpRight size={16}/></Link>)}</div>:<div className="fd-empty"><BookOpen size={28}/><h3>Todavía no hay publicaciones</h3><p>Las tareas, apuntes y avisos aparecerán aquí cuando el grupo los comparta.</p></div>;}
