import { createFileRoute } from "@tanstack/react-router";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { ArrowUpRight, Download, GraduationCap, Printer, CheckCircle2, LockKeyhole } from "lucide-react";
import { CreditRing } from "@/components/credit-ring";
import { Shell } from "@/components/shell";
import { PLAN_COURSES, PLAN_SOURCE, type PlanCourse } from "@/lib/study/plan";
import { validateProgress,summarizeProgress,missingPrerequisites,type StudyProgress,type CourseStatus } from "@/lib/study/progress";
import { loadStudyProgress,saveStudyProgress } from "@/lib/study/functions";
import { useCurrentUserState } from "@/lib/auth/use-current-user";
export const Route=createFileRoute("/plan-estudios")({component:StudyPlan});

function StudyPlan(){const{user}=useCurrentUserState();const client=useQueryClient();const key=["study-progress",user?.id];const query=useQuery({queryKey:key,queryFn:()=>loadStudyProgress(),enabled:!!user,retry:1});const progress=query.data?.progress??{};const summary=summarizeProgress(progress);const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[q,setQ]=useState("");const[view,setView]=useState("plan");const[filter,setFilter]=useState("todos");
 const editable=!!user&&!!query.data&&!busy;
 async function update(next:StudyProgress){if(!query.data||busy)return;setError("");setBusy(true);try{const valid=validateProgress(next);const data=await saveStudyProgress({data:{progress:valid,revision:query.data.revision}});client.setQueryData(key,data);}catch(e){setError(e instanceof Error?e.message:"No se pudo guardar el avance.");}finally{setBusy(false);}}
 function status(id:string,value:CourseStatus){void update({...progress,[id]:{...progress[id],status:value}});}
 function selectElective(id:string,semester:string){const next={...progress};if(!semester)delete next[id];else next[id]={status:next[id]?.status??"pendiente",semester:Number(semester) as 9|10};void update(next);}
 const match=(c:PlanCourse)=>`${c.code??""} ${c.name}`.toLocaleLowerCase("es").includes(q.toLocaleLowerCase("es"))&&(filter==="todos"||(progress[c.id]?.status??"pendiente")===filter);
 function exportCsv(){const rows=[["Identificador","Clave","Materia","Semestre","Tipo","Créditos","Estado"],...PLAN_COURSES.filter(c=>c.kind==="obligatoria"||progress[c.id]).map(c=>[c.id,c.code??"Consultar SIAE",c.name,String(c.semester??progress[c.id]?.semester??""),c.kind,String(c.credits),progress[c.id]?.status??"pendiente"])];const csv="\uFEFF"+rows.map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(",")).join("\r\n");const url=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download="mi-plan-derecho-2125.csv";a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 function courseCard(c:PlanCourse,catalog=false){const missing=missingPrerequisites(c.id,progress);const current=progress[c.id]?.status??"pendiente";return <article className={`fd-course-card status-${current}`} key={c.id}><div className="fd-course-top"><span>{c.code??(c.kind==="optativa"?"OPTATIVA":"CLAVE POR CONFIRMAR")}</span><b>{c.credits} créditos</b></div><h3>{c.name}</h3>{c.prerequisites.length?<details><summary>Seriación · {c.prerequisites.join(", ")}</summary>{c.prerequisites.map(code=><p key={code}>{code} · {PLAN_COURSES.find(p=>p.id===code)?.name??"Consultar SIAE"}</p>)}{missing.length?<p className="fd-warning">No marcada como aprobada en tu avance. Confirma los requisitos oficiales.</p>:<p>Requisito marcado como aprobado.</p>}</details>:<p className="fd-course-requirements">Sin requisito de inscripción indicado en la estructura consultada.</p>}{catalog||c.kind==="optativa"?<label className="fd-select-label">Selección personal<select value={progress[c.id]?.semester??""} disabled={!editable} onChange={e=>selectElective(c.id,e.target.value)}><option value="">No seleccionada</option><option value="9">Noveno semestre</option><option value="10">Décimo semestre</option></select></label>:null}{c.kind==="obligatoria"||progress[c.id]?<label className="fd-select-label">Mi avance<select value={current} disabled={!editable} onChange={e=>status(c.id,e.target.value as CourseStatus)}><option value="pendiente">Pendiente</option><option value="cursando">Cursando</option><option value="aprobada">Aprobada</option></select></label>:null}</article>;}
 return <Shell eyebrow="LICENCIATURA EN DERECHO · SUAYED · PLAN 2125" title="Tu carrera, de principio a fin." lead="Diez semestres para construir tu camino. Consulta todas las materias, revisa la seriación y lleva un registro personal de tu avance.">
  <section className="fd-plan-overview"><CreditRing credits={summary.credits}/><div><span className="fd-eyebrow">MI AVANCE PERSONAL</span><h2>{summary.credits}<small> / 450 créditos</small></h2><p>{user?`${summary.passed} materias marcadas como aprobadas. Este registro no es un historial académico oficial.`:"Inicia sesión para guardar tu avance. La consulta del plan es pública."}</p></div><div className="fd-plan-facts"><div><strong>51</strong><span>Obligatorias · 366 créditos</span></div><div><strong>12</strong><span>Optativas a cursar · 84 créditos</span></div><div><strong>87</strong><span>Opciones en el catálogo</span></div></div></section>
  {error||query.isError?<p className="fd-alert" role="alert">{error||"No se pudo cargar tu avance personal; las materias oficiales siguen disponibles."}</p>:null}{busy?<p className="fd-feed-status" role="status">Guardando avance…</p>:null}
  <div className="fd-plan-toolbar"><div className="fd-tabs"><button className={view==="plan"?"active":""} onClick={()=>setView("plan")}>Mapa por semestre</button><button className={view==="catalogo"?"active":""} onClick={()=>setView("catalogo")}>Catálogo de optativas</button></div><div className="fd-actions"><button className="fd-outline-button" onClick={exportCsv}><Download size={15}/>Exportar CSV</button><button className="fd-outline-button" onClick={()=>window.print()}><Printer size={15}/>Imprimir</button></div></div>
  <div className="fd-filter-row"><input className="fd-field" value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar materia o clave…" aria-label="Buscar materia o clave"/><select className="fd-field" value={filter} onChange={e=>setFilter(e.target.value)} aria-label="Filtrar materias por avance"><option value="todos">Todos los estados</option><option value="pendiente">Pendientes</option><option value="cursando">Cursando</option><option value="aprobada">Aprobadas</option></select><a className="fd-text-link" href={PLAN_SOURCE} target="_blank" rel="noopener noreferrer">Consultar SIAE <ArrowUpRight size={16}/></a></div>
  {view==="plan"?<div className="fd-semesters">{Array.from({length:10},(_,i)=>i+1).map(semester=>{const selected=PLAN_COURSES.filter(c=>c.semester===semester||(semester>=9&&c.kind==="optativa"&&progress[c.id]?.semester===semester));const visible=selected.filter(match);if(q&&!visible.length)return null;return <section key={semester} className="fd-semester"><div className="fd-semester-heading"><span>{String(semester).padStart(2,"0")}</span><div><h2>Semestre {semester}</h2><p>{semester<9?`${selected.length} obligatorias · ${selected.reduce((n,c)=>n+c.credits,0)} créditos`:`6 optativas · 42 créditos · ${selected.length} seleccionadas`}</p></div><GraduationCap size={23}/></div><div className="fd-course-grid">{visible.map(c=>courseCard(c))}{semester>=9&&!q&&filter==="todos"?Array.from({length:6-selected.length},(_,i)=><button className="fd-elective-slot" key={`slot-${i}`} onClick={()=>{setView("catalogo");window.scrollTo({top:0,behavior:"smooth"});}}><span>+</span><strong>Elige una optativa</strong><small>Consulta la oferta vigente de la DUA</small></button>):null}</div></section>;})}</div>:<><div className="fd-info-note"><LockKeyhole size={20}/><p>El catálogo oficial reúne 87 opciones, incluyendo cursos monográficos y movilidad. No significa que todas estén disponibles cada semestre. La distribución y la inscripción se confirman con la DUA. Las claves optativas no recuperadas de los controles del SIAE se dejan sin inventar.</p></div><div className="fd-course-grid fd-electives-grid">{PLAN_COURSES.filter(c=>c.kind==="optativa"&&match(c)).map(c=>courseCard(c,true))}</div></>}
  <div className="fd-plan-source"><CheckCircle2 size={19}/><p>Fuente: UNAM · DGAE · SIAE, estructura y seriación del plan 2125, consultada el 6 de octubre de 2026. Los nombres se presentan desarrollados para facilitar la lectura. Las claves no visibles en la fuente se indican por confirmar. El SIAE y las indicaciones de la DUA prevalecen sobre esta herramienta personal. <a href={PLAN_SOURCE} target="_blank" rel="noopener noreferrer">Ver estructura oficial completa.</a></p></div>
 </Shell>;
}
