import { createFileRoute, Link } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { CalendarCheck2, CalendarDays, CheckCircle2, ChevronLeft, ChevronRight, Clock3, ExternalLink, MapPin, Pencil, Trash2, UserRound, UsersRound, Vote, X } from "lucide-react";
import { useMemo, useState, type FormEvent } from "react";
import { Shell } from "@/components/shell";
import { PollInsights } from "@/components/poll-insights";
import { Button, Card, Field, FormBox, Input, Pill, Textarea, cn } from "@/components/ui";
import { canEditPublication, isModerator, useDirectory } from "@/components/directory";
import { formatLongDate, getTodayIso } from "@/lib/format";
import { createPoll, loadPolls, removePoll, removeVoteResponse, savePublicVote, updatePoll, updateVoteResponse, type ActivityPoll, type AvailabilityMode, type VoteResponse } from "@/lib/votaciones";

export const Route = createFileRoute("/votaciones")({ component: VotacionesPage });
const DEFAULT_PROMPT = "¿Qué día y hora puedes asistir?";
const WEEKDAYS = [{value:"lunes",label:"Lunes"},{value:"martes",label:"Martes"},{value:"miercoles",label:"Miércoles"},{value:"jueves",label:"Jueves"},{value:"viernes",label:"Viernes"},{value:"sabado",label:"Sábado"},{value:"domingo",label:"Domingo"}] as const;
const WEEKDAY_LABELS = Object.fromEntries(WEEKDAYS.map(day=>[day.value,day.label])) as Record<string,string>;
const WEEK_LABELS = ["Lun","Mar","Mié","Jue","Vie","Sáb","Dom"];
function normalizeHttpUrl(value:string){const clean=value.trim();return !clean?"":/^https?:\/\//i.test(clean)?clean:`https://${clean}`;}
function parseIso(iso:string){const [year,month,day]=iso.split("-").map(Number);return{year,month,day};}
function makeIso(year:number,month:number,day:number){return `${year}-${String(month).padStart(2,"0")}-${String(day).padStart(2,"0")}`;}
function monthLabel(iso:string){const{year,month}=parseIso(iso);return new Intl.DateTimeFormat("es-MX",{month:"long",year:"numeric",timeZone:"UTC"}).format(new Date(Date.UTC(year,month-1,1)));}
function shiftMonth(iso:string,delta:number){const{year,month}=parseIso(iso);const d=new Date(Date.UTC(year,month-1+delta,1));return makeIso(d.getUTCFullYear(),d.getUTCMonth()+1,1);}
function monthCells(iso:string){const{year,month}=parseIso(iso);const first=new Date(Date.UTC(year,month-1,1));const days=new Date(Date.UTC(year,month,0)).getUTCDate();return[...Array.from({length:(first.getUTCDay()+6)%7},()=>null),...Array.from({length:days},(_,i)=>makeIso(year,month,i+1))];}
function pollCalendarDate(poll:ActivityPoll){return poll.scheduledDate||poll.eventDate||null;}
function pollFields(data:FormData){return {title:String(data.get("title")??"").trim(),prompt:String(data.get("prompt")??DEFAULT_PROMPT).trim(),description:String(data.get("description")??"").trim(),scheduledDate:String(data.get("scheduledDate")??""),scheduledTime:String(data.get("scheduledTime")??"").trim(),locationText:String(data.get("locationText")??"").trim(),mapsUrl:normalizeHttpUrl(String(data.get("mapsUrl")??"")),notes:String(data.get("notes")??"").trim()};}

function VotacionesPage(){
 const{user,directory}=useDirectory();const admin=isModerator(directory);
 const pollsQuery=useQuery({queryKey:["activity-polls"],queryFn:()=>loadPolls(),staleTime:5000});const polls=pollsQuery.data??[];const today=getTodayIso();
 const[monthCursor,setMonthCursor]=useState(`${today.slice(0,7)}-01`);const[selectedDate,setSelectedDate]=useState<string|null>(null);const[selectedPollId,setSelectedPollId]=useState<number|null>(null);const[editingPollId,setEditingPollId]=useState<number|null>(null);const[editingResponseId,setEditingResponseId]=useState<number|null>(null);const[busy,setBusy]=useState(false);const[pageError,setPageError]=useState<string|null>(null);const[pageSuccess,setPageSuccess]=useState<string|null>(null);
 const selectedPoll=polls.find(p=>p.id===selectedPollId)??polls.find(p=>p.isOpen)??polls[0]??null;
 const activePolls=polls.filter(p=>p.isOpen);const scheduledPolls=polls.filter(p=>Boolean(pollCalendarDate(p)));const totalParticipants=polls.reduce((n,p)=>n+p.responses.length,0);
 const calendarCounts=useMemo(()=>{const counts=new Map<string,number>();for(const p of polls){const d=pollCalendarDate(p);if(d)counts.set(d,(counts.get(d)??0)+1);}return counts;},[polls]);
 const cells=useMemo(()=>monthCells(monthCursor),[monthCursor]);const selectedDatePolls=selectedDate?polls.filter(p=>pollCalendarDate(p)===selectedDate):[];
 const upcoming=scheduledPolls.filter(p=>(pollCalendarDate(p)??"")>=today).sort((a,b)=>(pollCalendarDate(a)??"").localeCompare(pollCalendarDate(b)??"")).slice(0,6);const undated=polls.filter(p=>!pollCalendarDate(p));
 async function refresh(){await pollsQuery.refetch();}
 function choosePoll(p:ActivityPoll){setSelectedPollId(p.id);setEditingPollId(null);setEditingResponseId(null);const d=pollCalendarDate(p);if(d){setSelectedDate(d);setMonthCursor(`${d.slice(0,7)}-01`);}window.setTimeout(()=>document.getElementById(`votacion-${p.id}`)?.scrollIntoView({behavior:"smooth",block:"start"}),0);}
 function chooseDate(d:string){setSelectedDate(d);const first=polls.find(p=>pollCalendarDate(p)===d);if(first)setSelectedPollId(first.id);}
 async function onCreate(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;setBusy(true);setPageError(null);setPageSuccess(null);try{const result=await createPoll({data:pollFields(new FormData(form))});form.reset();setSelectedPollId(result.id);setPageSuccess("Votación creada correctamente.");await refresh();}catch(e){setPageError(e instanceof Error?e.message:"No se pudo crear la votación.");}finally{setBusy(false);}}
 async function onUpdate(event:FormEvent<HTMLFormElement>,poll:ActivityPoll){event.preventDefault();const data=new FormData(event.currentTarget);setBusy(true);setPageError(null);setPageSuccess(null);try{await updatePoll({data:{id:poll.id,...pollFields(data),isOpen:data.get("isOpen")==="on"}});setEditingPollId(null);setPageSuccess("Votación actualizada.");await refresh();}catch(e){setPageError(e instanceof Error?e.message:"No se pudo actualizar la votación.");}finally{setBusy(false);}}
 async function onRemove(poll:ActivityPoll){if(!window.confirm(`¿Eliminar la votación “${poll.title}” y todas sus respuestas?`))return;setBusy(true);setPageError(null);setPageSuccess(null);try{await removePoll({data:{id:poll.id}});if(selectedPollId===poll.id)setSelectedPollId(null);setPageSuccess("Votación eliminada.");await refresh();}catch(e){setPageError(e instanceof Error?e.message:"No se pudo eliminar la votación.");}finally{setBusy(false);}}
 return <Shell eyebrow="Votaciones · Grupo 9114" title="Votaciones, acuerdos y disponibilidad del grupo." lead="Consulta el calendario, compara las propuestas y distingue la tendencia de las respuestas del acuerdo final.">
  <Card className="unam-hero-card hero-glow mb-7"><div className="grid gap-5 lg:grid-cols-[1fr_auto] lg:items-center"><div><p className="text-xs font-semibold uppercase tracking-[0.15em] text-bg/60">Participación abierta</p><h2 className="mt-2 font-display text-3xl">Organiza actividades y encuentra la mejor fecha.</h2><p className="mt-2 max-w-2xl text-sm text-bg/75">El calendario muestra fechas calendarizadas. Las gráficas muestran disponibilidad y no fijan acuerdos automáticamente.</p></div><div className="grid grid-cols-3 gap-2 text-center"><HeroStat value={activePolls.length} label="actividades activas"/><HeroStat value={scheduledPolls.length} label="con fecha"/><HeroStat value={totalParticipants} label="participaciones"/></div></div></Card>
  {pageError?<p role="alert" className="mb-4 rounded-lg border border-danger/20 bg-red-50 px-4 py-3 text-sm text-danger">{pageError}</p>:null}{pageSuccess?<p role="status" className="mb-4 rounded-lg bg-forest-soft px-4 py-3 text-sm font-medium text-forest-deep">{pageSuccess}</p>:null}
  <section className="fd-calendar-layout">
   <Card className="fd-compact-calendar overflow-hidden p-0"><div className="unam-hero px-5 py-5 sm:px-6"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[0.15em] text-white/65">Calendario de compromisos</p><h2 className="mt-1 font-display text-3xl capitalize text-white">{monthLabel(monthCursor)}</h2><p className="mt-1 text-sm text-white/70">Los círculos dorados indican actividades calendarizadas.</p></div><div className="flex gap-2"><button type="button" onClick={()=>setMonthCursor(shiftMonth(monthCursor,-1))} className="grid size-11 place-items-center rounded-full border border-white/15 bg-white/10 text-white" aria-label="Mes anterior"><ChevronLeft className="size-5"/></button><button type="button" onClick={()=>{setMonthCursor(`${today.slice(0,7)}-01`);setSelectedDate(today);}} className="rounded-full border border-white/15 bg-white/10 px-4 text-sm font-semibold text-white">Hoy</button><button type="button" onClick={()=>setMonthCursor(shiftMonth(monthCursor,1))} className="grid size-11 place-items-center rounded-full border border-white/15 bg-white/10 text-white" aria-label="Mes siguiente"><ChevronRight className="size-5"/></button></div></div></div>
    <div className="p-4 sm:p-5"><div className="grid grid-cols-7 gap-1 text-center text-[11px] font-semibold uppercase tracking-[0.08em] text-muted">{WEEK_LABELS.map(label=><span key={label} className="py-2">{label}</span>)}</div><div className="grid grid-cols-7 gap-1">{cells.map((d,i)=>{if(!d)return <span key={`blank-${i}`} className="aspect-square"/>;const count=calendarCounts.get(d)??0;const selected=selectedDate===d;return <button key={d} type="button" onClick={()=>chooseDate(d)} aria-label={`${formatLongDate(d)}: ${count} actividades`} className={cn("relative grid aspect-square place-items-center rounded-full text-sm font-semibold transition-all",selected?"bg-forest text-white shadow-md":count?"bg-clay/10 text-ink hover:bg-clay/20":d===today?"bg-forest-soft text-forest-deep":"text-ink-soft hover:bg-bg-warm")}>{Number(d.slice(-2))}{count?<span className={cn("absolute -bottom-0.5 -right-0.5 grid min-w-5 place-items-center rounded-full px-1 py-0.5 text-[10px] font-bold",selected?"bg-clay text-white":"bg-clay/20 text-clay")}>{count}</span>:null}</button>;})}</div></div>
   </Card>
   <Card><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-clay">{selectedDate?"Fecha seleccionada":"Próximas actividades"}</p><h2 className="mt-1 font-display text-2xl">{selectedDate?formatLongDate(selectedDate):"Compromisos del grupo"}</h2></div><Pill tone="forest">{selectedDate?selectedDatePolls.length:upcoming.length}</Pill></div><div className="mt-4 grid gap-2">{(selectedDate?selectedDatePolls:upcoming).map(p=><button key={p.id} type="button" onClick={()=>choosePoll(p)} className={cn("w-full rounded-xl border p-3 text-left transition-all hover:-translate-y-0.5 hover:shadow-sm",selectedPoll?.id===p.id?"border-forest bg-forest-soft":"border-line bg-bg-warm/55")}><div className="flex items-center justify-between gap-3"><div className="min-w-0"><p className="font-semibold text-ink">{p.title}</p><p className="mt-1 text-xs text-muted">{pollCalendarDate(p)?formatLongDate(pollCalendarDate(p)!):"Sin fecha"}{p.scheduledTime||p.eventTime?` · ${p.scheduledTime||p.eventTime}`:""}</p></div><span className="shrink-0 text-xs font-semibold text-forest">Ver votación</span></div></button>)}{!(selectedDate?selectedDatePolls:upcoming).length?<p className="rounded-lg bg-bg-warm p-4 text-sm text-muted">No hay actividades para esta selección.</p>:null}</div>{undated.length?<div className="mt-5 border-t border-line pt-4"><p className="text-xs font-semibold uppercase tracking-[0.1em] text-muted">Sin fecha pactada</p><div className="mt-2 flex flex-wrap gap-2">{undated.map(p=><button key={p.id} type="button" onClick={()=>choosePoll(p)} className="rounded-full border border-line bg-white px-3 py-2 text-xs font-semibold text-forest">{p.title}</button>)}</div></div>:null}</Card>
  </section>
  {polls.length?<div className="mb-7"><label className="fd-select-label">Consultar cualquier votación, también las cerradas<select value={selectedPoll?.id??""} onChange={e=>{const p=polls.find(v=>v.id===Number(e.target.value));if(p)choosePoll(p);}}>{polls.map(p=><option value={p.id} key={p.id}>{p.title} · {p.isOpen?"Abierta":"Cerrada"}</option>)}</select></label></div>:null}
  {admin?<div className="mb-7"><FormBox title="Nueva votación independiente" onSubmit={onCreate}><p className="text-sm text-muted">También puedes abrir una votación ligada a una actividad desde Agenda.</p><PollDetailsFields/><Button type="submit" disabled={busy}><Vote className="mr-2 size-4"/>Crear votación</Button></FormBox></div>:null}
  {pollsQuery.isPending?<Card><p className="text-sm text-muted">Cargando votaciones…</p></Card>:null}{pollsQuery.isError?<Card><p role="alert" className="text-sm text-danger">No se pudieron cargar las votaciones. Revisa la conexión y las migraciones de Neon.</p></Card>:null}
  {selectedPoll?<PollCard key={selectedPoll.id} poll={selectedPoll} canEditPoll={canEditPublication(directory,user?.id,selectedPoll.createdBy)} admin={admin} editing={editingPollId===selectedPoll.id} busy={busy} editingResponseId={editingResponseId} onStartEdit={()=>setEditingPollId(selectedPoll.id)} onCancelEdit={()=>setEditingPollId(null)} onUpdatePoll={e=>onUpdate(e,selectedPoll)} onRemovePoll={()=>void onRemove(selectedPoll)} onRefresh={refresh} onBusy={setBusy} onError={setPageError} onSuccess={setPageSuccess} onEditResponse={setEditingResponseId}/>:!pollsQuery.isPending?<Card><p className="font-display text-2xl">Todavía no hay votaciones.</p><p className="mt-2 text-sm text-muted">Las votaciones abiertas desde Agenda aparecerán aquí.</p><Link to="/agenda" className="mt-4 inline-flex text-sm font-semibold text-forest">Ver actividades</Link></Card>:null}
 </Shell>;
}
function HeroStat({value,label}:{value:number;label:string}){return <div className="min-w-24 rounded-xl border border-white/10 bg-white/[0.07] px-3 py-4 text-center"><p className="font-display text-3xl leading-none">{value}</p><p className="mt-1 text-[10px] uppercase tracking-[0.1em] text-bg/60">{label}</p></div>;}
function PollDetailsFields({poll}:{poll?:ActivityPoll}){return <>
 <Field label="Título"><Input name="title" required maxLength={180} defaultValue={poll?.title??""} placeholder="Curso de argumentación jurídica"/></Field>
 <Field label="Pregunta"><Input name="prompt" required maxLength={300} defaultValue={poll?.prompt??DEFAULT_PROMPT}/></Field>
 <Field label="Descripción" hint="Opcional"><Textarea name="description" maxLength={2400} defaultValue={poll?.description??""} placeholder="Información, objetivo y condiciones de la actividad."/></Field>
 <div className="grid gap-3 sm:grid-cols-2"><Field label="Fecha pactada" hint="Opcional"><Input name="scheduledDate" type="date" defaultValue={poll?.scheduledDate??poll?.eventDate??""}/></Field><Field label="Horario pactado" hint="Opcional"><Input name="scheduledTime" maxLength={80} defaultValue={poll?.scheduledTime??poll?.eventTime??""} placeholder="17:00–19:00"/></Field></div>
 <Field label="Lugar / referencia" hint="Opcional"><Input name="locationText" maxLength={240} defaultValue={poll?.locationText??poll?.eventPlace??""} placeholder="Facultad, salón o punto de reunión"/></Field>
 <Field label="Liga de Google Maps" hint="Opcional"><Input name="mapsUrl" type="url" defaultValue={poll?.mapsUrl??""} placeholder="https://maps.app.goo.gl/..."/></Field>
 <Field label="Comentarios o notas" hint="Opcional"><Textarea name="notes" maxLength={4000} defaultValue={poll?.notes??""} placeholder="Costo, materiales, contacto e indicaciones."/></Field>
 </>;}
type PollCardProps={poll:ActivityPoll;canEditPoll:boolean;admin:boolean;editing:boolean;busy:boolean;editingResponseId:number|null;onStartEdit:()=>void;onCancelEdit:()=>void;onUpdatePoll:(e:FormEvent<HTMLFormElement>)=>Promise<void>;onRemovePoll:()=>void;onRefresh:()=>Promise<void>;onBusy:(v:boolean)=>void;onError:(v:string|null)=>void;onSuccess:(v:string|null)=>void;onEditResponse:(id:number|null)=>void};
function PollCard({poll,canEditPoll,admin,editing,busy,editingResponseId,onStartEdit,onCancelEdit,onUpdatePoll,onRemovePoll,onRefresh,onBusy,onError,onSuccess,onEditResponse}:PollCardProps){
 const[localMessage,setLocalMessage]=useState<string|null>(null);const[availabilityMode,setAvailabilityMode]=useState<AvailabilityMode>("specific");const[preferredWeekdays,setPreferredWeekdays]=useState<string[]>([]);
 // A calendarized date/time is distinct from the statistical trend. Never mix marginal maxima.
 const displayDate=poll.scheduledDate||poll.eventDate||null;const displayTime=poll.scheduledTime||poll.eventTime||null;const location=poll.locationText||poll.eventPlace||null;
 async function onVote(event:FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget);onBusy(true);onError(null);onSuccess(null);setLocalMessage(null);try{await savePublicVote({data:{pollId:poll.id,participantName:String(data.get("participantName")??"").trim(),availabilityMode,availableDate:String(data.get("availableDate")??""),availableTime:String(data.get("availableTime")??""),preferredWeekdays:data.getAll("preferredWeekdays").map(String),note:String(data.get("note")??"").trim(),website:String(data.get("website")??"")}});setLocalMessage("Tu disponibilidad quedó guardada.");await onRefresh();}catch(e){onError(e instanceof Error?e.message:"No se pudo guardar tu disponibilidad.");}finally{onBusy(false);}}
 async function onUpdateResponse(event:FormEvent<HTMLFormElement>,response:VoteResponse){event.preventDefault();const data=new FormData(event.currentTarget);onBusy(true);onError(null);onSuccess(null);try{await updateVoteResponse({data:{id:response.id,participantName:String(data.get("participantName")??"").trim(),availabilityMode:String(data.get("availabilityMode")??"specific") as AvailabilityMode,availableDate:String(data.get("availableDate")??""),availableTime:String(data.get("availableTime")??""),preferredWeekdays:data.getAll("preferredWeekdays").map(String),note:String(data.get("note")??"").trim()}});onEditResponse(null);onSuccess("Participación actualizada.");await onRefresh();}catch(e){onError(e instanceof Error?e.message:"No se pudo editar la participación.");}finally{onBusy(false);}}
 async function onRemoveResponse(response:VoteResponse){if(!window.confirm(`¿Quitar a ${response.participantName} de esta votación?`))return;onBusy(true);onError(null);onSuccess(null);try{await removeVoteResponse({data:{id:response.id}});onSuccess("Participación eliminada.");await onRefresh();}catch(e){onError(e instanceof Error?e.message:"No se pudo eliminar la participación.");}finally{onBusy(false);}}
 return <Card id={`votacion-${poll.id}`} className="scroll-mt-6 overflow-hidden p-0">
  <div className="border-b border-line p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><Pill tone={poll.isOpen?"forest":"neutral"}>{poll.isOpen?"Abierta":"Cerrada"}</Pill><Pill><UsersRound className="mr-1 size-3"/>{poll.responses.length} personas</Pill>{poll.scheduledDate?<Pill tone="clay"><CalendarCheck2 className="mr-1 size-3"/>Fecha pactada</Pill>:null}</div><h2 className="mt-3 font-display text-3xl">{poll.title}</h2><p className="mt-2 font-medium text-forest">{poll.prompt}</p>{poll.description?<p className="mt-2 max-w-3xl text-sm leading-relaxed text-muted">{poll.description}</p>:null}<div className="mt-3 flex flex-wrap items-center gap-x-4 gap-y-2 text-xs text-muted">{displayDate?<span className="inline-flex items-center gap-1"><CalendarDays className="size-3.5"/>{formatLongDate(displayDate)}</span>:null}{displayTime?<span className="inline-flex items-center gap-1"><Clock3 className="size-3.5"/>{displayTime}</span>:null}{location?<span className="inline-flex items-center gap-1"><MapPin className="size-3.5"/>{location}</span>:null}{poll.mapsUrl?<a href={poll.mapsUrl} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-1 font-semibold text-forest"><ExternalLink className="size-3.5"/>Abrir Google Maps</a>:null}</div>{poll.notes?<div className="mt-4 rounded-lg border border-line bg-bg-warm/55 p-3 text-sm leading-relaxed text-ink-soft"><strong className="text-ink">Notas:</strong> {poll.notes}</div>:null}</div><div className="flex flex-wrap gap-2">{canEditPoll?<button type="button" disabled={busy} onClick={onStartEdit} className="inline-flex min-h-10 items-center gap-1.5 rounded-md border border-line bg-white px-3 text-xs font-semibold text-forest"><Pencil className="size-3.5"/>Editar</button>:null}{admin?<button type="button" disabled={busy} onClick={onRemovePoll} className="inline-flex min-h-10 items-center gap-1.5 rounded-md border border-danger/20 bg-red-50 px-3 text-xs font-semibold text-danger"><Trash2 className="size-3.5"/>Eliminar</button>:null}</div></div>
   {editing?<form onSubmit={onUpdatePoll} className="mt-5 grid gap-3 rounded-xl border border-line bg-bg-warm/60 p-4"><div className="flex items-center justify-between"><p className="font-semibold">Editar votación</p><button type="button" onClick={onCancelEdit} className="inline-flex items-center gap-1 text-xs font-semibold text-forest"><X className="size-3.5"/>Cancelar</button></div><PollDetailsFields poll={poll}/><label className="flex items-center gap-2 text-sm font-medium"><input name="isOpen" type="checkbox" defaultChecked={poll.isOpen} className="size-4"/>Aceptar nuevas participaciones</label><Button type="submit" disabled={busy}>Guardar cambios</Button></form>:null}
  </div>
  <PollInsights poll={poll}/>
  <div className="grid gap-6 p-5 sm:p-6 xl:grid-cols-[minmax(19rem,.8fr)_minmax(0,1.2fr)]"><div><h3 className="font-display text-2xl">Personas registradas</h3><div className="mt-3 grid gap-2">{poll.responses.map(response=><div key={response.id} className="rounded-lg border border-line bg-white p-3">{editingResponseId===response.id&&admin?<ResponseEditForm response={response} busy={busy} onSubmit={e=>void onUpdateResponse(e,response)} onCancel={()=>onEditResponse(null)}/>:<div className="flex items-start justify-between gap-3"><div><p className="inline-flex items-center gap-1.5 font-semibold"><UserRound className="size-4 text-forest"/>{response.participantName}</p><p className="mt-1 text-sm text-muted">{describeAvailability(response)}</p>{response.note?<p className="mt-1 text-xs text-muted">{response.note}</p>:null}</div>{admin?<div className="flex gap-1"><button type="button" disabled={busy} onClick={()=>onEditResponse(response.id)} className="grid size-8 place-items-center rounded-md border border-line text-forest" aria-label="Editar participación"><Pencil className="size-3.5"/></button><button type="button" disabled={busy} onClick={()=>void onRemoveResponse(response)} className="grid size-8 place-items-center rounded-md border border-danger/20 text-danger" aria-label="Eliminar participación"><Trash2 className="size-3.5"/></button></div>:null}</div>}</div>)}{!poll.responses.length?<p className="text-sm text-muted">La lista aparecerá conforme se apunten.</p>:null}</div></div>
   <div>{poll.isOpen?<FormBox title="Anotar mi disponibilidad" onSubmit={onVote}><div className="rounded-lg border border-forest/10 bg-forest-soft p-3 text-sm text-forest-deep"><strong>No necesitas registrarte.</strong> Puedes indicar una fecha exacta, marcar varios días o elegir <strong>Me adapto</strong>.</div><Field label="Tu nombre"><Input name="participantName" required minLength={2} maxLength={80} placeholder="Nombre y apellido"/></Field><AvailabilityFields mode={availabilityMode} onModeChange={setAvailabilityMode} selectedWeekdays={preferredWeekdays} onWeekdaysChange={setPreferredWeekdays} defaultDate={poll.scheduledDate??poll.eventDate??getTodayIso()}/><Field label="Comentario" hint="Opcional"><Textarea name="note" maxLength={240} placeholder="Ej. También puedo una hora después."/></Field><div className="hidden" aria-hidden="true"><Input name="website" tabIndex={-1} autoComplete="off"/></div>{localMessage?<p role="status" className="inline-flex items-center gap-2 text-sm font-medium text-forest"><CheckCircle2 className="size-4"/>{localMessage}</p>:null}<Button type="submit" disabled={busy}><Vote className="mr-2 size-4"/>Guardar mi disponibilidad</Button></FormBox>:<Card className="bg-bg-warm/60"><p className="font-display text-2xl">Votación cerrada</p><p className="mt-2 text-sm text-muted">La lista y los resultados siguen visibles, pero ya no se aceptan nuevas participaciones.</p></Card>}</div>
  </div>
 </Card>;
}
function ResponseEditForm({response,busy,onSubmit,onCancel}:{response:VoteResponse;busy:boolean;onSubmit:(e:FormEvent<HTMLFormElement>)=>void;onCancel:()=>void}){const[mode,setMode]=useState<AvailabilityMode>(response.availabilityMode);const[weekdays,setWeekdays]=useState<string[]>(response.preferredWeekdays);return <form onSubmit={onSubmit} className="grid gap-3"><Field label="Nombre"><Input name="participantName" required minLength={2} maxLength={80} defaultValue={response.participantName}/></Field><AvailabilityFields mode={mode} onModeChange={setMode} selectedWeekdays={weekdays} onWeekdaysChange={setWeekdays} defaultDate={response.availableDate??getTodayIso()} defaultTime={response.availableTime??""}/><Field label="Nota" hint="Opcional"><Input name="note" maxLength={240} defaultValue={response.note??""}/></Field><div className="flex gap-2"><Button type="submit" disabled={busy}>Guardar</Button><button type="button" onClick={onCancel} className="px-3 text-xs font-semibold text-muted">Cancelar</button></div></form>;}
function AvailabilityFields({mode,onModeChange,selectedWeekdays,onWeekdaysChange,defaultDate,defaultTime=""}:{mode:AvailabilityMode;onModeChange:(mode:AvailabilityMode)=>void;selectedWeekdays:string[];onWeekdaysChange:(days:string[])=>void;defaultDate:string;defaultTime?:string}){
 function toggleWeekday(day:string){onWeekdaysChange(selectedWeekdays.includes(day)?selectedWeekdays.filter(d=>d!==day):[...selectedWeekdays,day]);}
 return <div className="grid gap-3"><div><p className="mb-2 text-sm font-medium text-ink-soft">Cómo te acomoda</p><div className="grid gap-2 sm:grid-cols-3">{[{value:"specific" as const,label:"Fecha y hora"},{value:"flexible" as const,label:"Me adapto"},{value:"weekdays" as const,label:"Varios días"}].map(option=><button key={option.value} type="button" onClick={()=>onModeChange(option.value)} className={mode===option.value?"min-h-11 rounded-md border border-forest bg-forest px-3 text-sm font-semibold text-white shadow-sm":"min-h-11 rounded-md border border-line bg-white px-3 text-sm font-semibold text-ink-soft transition hover:border-forest/40"}>{option.label}</button>)}</div><input type="hidden" name="availabilityMode" value={mode}/></div>
 {mode==="specific"?<div className="grid grid-cols-2 gap-3"><Field label="Día disponible"><Input name="availableDate" type="date" required defaultValue={defaultDate}/></Field><Field label="Hora disponible"><Input name="availableTime" type="time" required defaultValue={defaultTime}/></Field></div>:null}
 {mode==="flexible"?<div className="rounded-lg border border-forest/15 bg-forest-soft px-4 py-3 text-sm text-forest-deep"><strong>Me adapto.</strong> No necesitas seleccionar día ni hora; quedará registrado que puedes ajustarte a la opción que el grupo decida.</div>:null}
 {mode==="weekdays"?<div className="grid gap-3 rounded-lg border border-line bg-white p-3"><div><p className="text-sm font-medium text-ink-soft">Días que te funcionan</p><p className="mt-1 text-xs text-muted">Puedes marcar varios días de la semana.</p></div><div className="flex flex-wrap gap-2">{WEEKDAYS.map(day=>{const selected=selectedWeekdays.includes(day.value);return <label key={day.value} className={selected?"cursor-pointer rounded-full border border-forest bg-forest px-3 py-2 text-xs font-semibold text-white":"cursor-pointer rounded-full border border-line bg-bg-warm px-3 py-2 text-xs font-semibold text-ink-soft"}><input type="checkbox" name="preferredWeekdays" value={day.value} checked={selected} onChange={()=>toggleWeekday(day.value)} className="sr-only"/>{day.label}</label>;})}</div><Field label="Hora preferida" hint="Opcional"><Input name="availableTime" type="time" defaultValue={defaultTime}/></Field></div>:null}</div>;
}
function describeAvailability(response:VoteResponse){if(response.availabilityMode==="flexible")return "Me adapto · cualquier día y hora";if(response.availabilityMode==="weekdays"){const days=response.preferredWeekdays.map(d=>WEEKDAY_LABELS[d]??d).join(", ");return `${days||"Varios días"}${response.availableTime?` · Preferencia ${response.availableTime}`:" · cualquier hora"}`;}return `${response.availableDate?formatLongDate(response.availableDate):"Fecha por definir"}${response.availableTime?` · ${response.availableTime}`:""}`;}
