import {useEffect,useState} from 'react';
import {RotateCcw,CheckCircle2,ChevronRight,Eye,Trophy} from 'lucide-react';
import {type GameSubject,type StudyCard} from '@/lib/games/bank';
import {boardAnswer,quizDeck,shuffled,type PracticeAnswer,type GameMode} from '@/lib/games/engine';
export function Source({card}:{card:StudyCard}){return <details className="fd-study-source"><summary>Fuente y contexto</summary><p>{card.source}</p>{card.sourceUrl?<a href={card.sourceUrl} target="_blank" rel="noopener noreferrer">Consultar programa público de la UNAM ↗</a>:null}<p>{card.definition}</p></details>;}
type Props={subject:GameSubject;seed:number;mode:GameMode;onComplete:(answers:PracticeAnswer[])=>void};
function Finish({correct,total}:{correct:number;total:number}){return <div className="fd-game-finish" role="status"><Trophy size={36}/><h3>Ronda terminada</h3><strong>{correct} / {total}</strong><p>Resultado de práctica. No cambia tus materias aprobadas ni tus créditos.</p></div>;}
export function QuizActivity({subject,seed,mode,onComplete}:Props){
 const[deck]=useState(()=>quizDeck(subject.cards,seed,5));const[index,setIndex]=useState(0),[selected,setSelected]=useState<string|null>(null),[answers,setAnswers]=useState<PracticeAnswer[]>([]),[finished,setFinished]=useState(false);const q=deck[index];const vf=mode==='verdadero-falso';const compared=vf&&((seed+index)%2===0)?deck[index].options.find(c=>c.id!==q.card.id)!:q.card;const correctValue=vf?(compared.id===q.card.id?'verdadero':'falso'):q.card.term;
 function answer(value:string){if(selected!==null)return;setSelected(value);setAnswers(a=>[...a,{id:q.card.id,value,...(vf?{comparedId:compared.id}:{})}]);}
 function next(){if(index+1===deck.length){setFinished(true);onComplete(answers);}else{setIndex(index+1);setSelected(null);}}
 if(finished){const n=answers.filter((a,i)=>vf?(a.value==='verdadero')===(a.id===a.comparedId):a.value===deck[i].card.term).length;return <><Finish correct={n} total={deck.length}/><div className="fd-quiz-review">{deck.map((r,i)=><div key={r.card.id}><strong>{i+1}. {r.card.term}</strong><p>{r.card.definition}</p><Source card={r.card}/></div>)}</div></>;}
 return <div className="fd-game-panel"><p className="fd-eyebrow">PREGUNTA {index+1} DE {deck.length}</p><progress value={index} max={deck.length} aria-label="Avance del cuestionario"/><h3>{vf?`${q.card.term}: ${compared.definition}`:q.card.question}</h3>{vf?<p>¿La asociación entre el concepto y la descripción es correcta según la fuente?</p>:null}<div className="fd-quiz-options">{(vf?['verdadero','falso']:q.options.map(c=>c.term)).map((value,i)=><button key={value} type="button" disabled={selected!==null} onClick={()=>answer(value)} className={selected!==null?(value===correctValue?'is-correct':value===selected?'is-wrong':''):''}><b>{String.fromCharCode(65+i)}</b>{value==='verdadero'?'Verdadero':value==='falso'?'Falso':value}</button>)}</div>{selected!==null?<div className="fd-answer-feedback" role="status"><strong>{selected===correctValue?'Respuesta correcta.':'Repasemos esta asociación.'}</strong><p>{q.card.definition}</p><Source card={q.card}/><button className="fd-primary-button" type="button" onClick={next}>{index+1===deck.length?'Ver resultado':'Siguiente pregunta'}<ChevronRight size={17}/></button></div>:null}</div>;
}
export function Flashcards({subject,seed,onComplete}:Props){const[cards]=useState(()=>shuffled(subject.cards,seed));const[index,setIndex]=useState(0),[flipped,setFlipped]=useState(false),[known,setKnown]=useState<string[]>([]),[finished,setFinished]=useState(false);const c=cards[index];function next(){setIndex((index+1)%cards.length);setFlipped(false);}if(finished)return <><Finish correct={known.length} total={cards.length}/><p className="fd-muted">Autoevaluación: fichas que marcaste como recordadas, no una verificación de conocimientos.</p></>;return <div className="fd-game-panel"><p className="fd-eyebrow">FICHA {index+1} DE {cards.length} · {known.length} MARCADAS PARA ESTA RONDA</p><button type="button" className={`fd-flashcard ${flipped?'is-revealed':''}`} onClick={()=>setFlipped(!flipped)} aria-pressed={flipped}><span>{flipped?'DESCRIPCIÓN SEGÚN LA FUENTE':'CONCEPTO'}</span><strong>{flipped?c.definition:c.term}</strong><small><RotateCcw size={16}/>Toca o pulsa Enter para girar</small></button>{flipped?<Source card={c}/>:null}<div className="fd-actions"><button className="fd-outline-button" onClick={next}>Seguir repasando</button><button className="fd-primary-button" onClick={()=>{setKnown(a=>a.includes(c.id)?a:[...a,c.id]);next();}}><CheckCircle2 size={17}/>La recuerdo</button><button className="fd-outline-button" onClick={()=>{setFinished(true);onComplete(cards.map(card=>({id:card.id,value:known.includes(card.id)?card.term:''})));}}>Terminar repaso</button></div><p className="fd-muted">Autoevaluación, no calificación. Al terminar, se guarda cuántas fichas marcaste como recordadas.</p></div>;}
export function MemoryActivity({subject,seed,onComplete}:Props){
 const[pairs]=useState(()=>shuffled(subject.cards,seed).slice(0,4));const[deck]=useState(()=>shuffled(pairs.flatMap(c=>[{key:c.id+'-t',id:c.id,text:c.term},{key:c.id+'-d',id:c.id,text:c.definition}]),seed+3));const[open,setOpen]=useState<number[]>([]),[matched,setMatched]=useState<string[]>([]),[moves,setMoves]=useState(0);const finished=matched.length===pairs.length;
 useEffect(()=>{if(open.length!==2)return;const timer=setTimeout(()=>setOpen([]),1000);return()=>clearTimeout(timer);},[open]);
 function flip(i:number){if(finished||open.length===2||open.includes(i)||matched.includes(deck[i].id))return;const next=[...open,i];setOpen(next);if(next.length===2){setMoves(v=>v+1);if(deck[next[0]].id===deck[next[1]].id){const ids=[...matched,deck[i].id];setMatched(ids);setOpen([]);if(ids.length===pairs.length)onComplete(pairs.map(c=>({id:c.id,value:c.term})));}}}
 return <div className="fd-game-panel"><p>Une cada concepto con su descripción. {matched.length} / {pairs.length} parejas · {moves} intentos.</p><div className="fd-memory-grid">{deck.map((c,i)=>{const show=open.includes(i)||matched.includes(c.id);return <button key={c.key} type="button" aria-label={show?c.text:`Carta ${i+1}, oculta`} disabled={matched.includes(c.id)} onClick={()=>flip(i)} className={show?'is-revealed':''}>{show?c.text:<><span>FD</span><small>Voltear</small></>}</button>;})}</div>{finished?<><Finish correct={pairs.length} total={pairs.length}/>{pairs.map(c=><Source key={c.id} card={c}/>)}</>:null}</div>;
}
export function MatchActivity({subject,seed,onComplete}:Props){const[cards]=useState(()=>shuffled(subject.cards,seed).slice(0,4)),[right]=useState(()=>shuffled(cards,seed+8));const[selected,setSelected]=useState<string|null>(null),[matched,setMatched]=useState<string[]>([]),[feedback,setFeedback]=useState('');function match(id:string){if(!selected)return;if(selected===id){const next=[...matched,id];setMatched(next);setFeedback('Pareja correcta.');if(next.length===cards.length)onComplete(cards.map(c=>({id:c.id,value:c.term})));}else setFeedback('No corresponde. Revisa los conceptos e inténtalo otra vez.');setSelected(null);}return <div className="fd-game-panel"><p>Selecciona un concepto y después su descripción. No hace falta arrastrar.</p><div className="fd-match-columns"><div>{cards.map(c=><button type="button" key={c.id} className={selected===c.id?'is-selected':''} aria-pressed={selected===c.id} disabled={matched.includes(c.id)} onClick={()=>setSelected(c.id)}>{matched.includes(c.id)?'✓ ':''}{c.term}</button>)}</div><div>{right.map(c=><button type="button" key={c.id} disabled={!selected||matched.includes(c.id)} onClick={()=>match(c.id)}>{c.definition}</button>)}</div></div><p role="status">{feedback}</p>{matched.length===cards.length?<><Finish correct={cards.length} total={cards.length}/>{cards.map(c=><Source card={c} key={c.id}/>)}</>:null}</div>;}
export function BoardActivity({subject,onComplete}:Props){const[value,setValue]=useState(''),[found,setFound]=useState<number[]>([]),[strikes,setStrikes]=useState(0),[feedback,setFeedback]=useState(''),[reveal,setReveal]=useState(false);const done=reveal||strikes>=3||found.length===subject.board.answers.length;function answer(){if(done)return;const index=boardAnswer(subject.id,value);if(index>=0&&found.includes(index)){setFeedback('Esa respuesta ya está en el tablero; no pierdes intento.');return;}if(index<0){setStrikes(n=>n+1);setFeedback('No coincide con las respuestas de esta fuente. Prueba otro concepto.');if(strikes+1===3)finish(found);}else{const next=[...found,index];setFound(next);setFeedback('¡Casilla descubierta!');if(next.length===subject.board.answers.length)finish(next);}setValue('');}function finish(ids:number[]){onComplete(subject.board.answers.map(([label],i)=>({id:String(i),value:ids.includes(i)?label:''})));}return <div className="fd-game-panel fd-law-board"><p className="fd-eyebrow">EL TABLERO JURÍDICO · RETO DE RESPUESTAS</p><h3>{subject.board.prompt}</h3><p className="fd-study-notice">Juego inspirado en los concursos de tablero. No hubo una encuesta a 100 alumnos: las casillas proceden del material citado. Cada acierto vale 10 puntos didácticos, no popularidad.</p><div className="fd-board-score"><strong>{found.length*10} puntos</strong><span>{strikes} / 3 intentos fallidos</span></div><div className="fd-board-slots">{subject.board.answers.map(([label],i)=><div key={label} className={found.includes(i)?'is-correct':''}><b>{i+1}</b><span>{found.includes(i)||done?label:'Respuesta por descubrir'}</span><strong>{found.includes(i)?'+10':''}</strong></div>)}</div><form onSubmit={e=>{e.preventDefault();answer();}}><label>Tu respuesta<input className="fd-field" maxLength={160} value={value} onChange={e=>setValue(e.target.value)} disabled={done} placeholder="Escribe un concepto…" autoComplete="off"/></label><button className="fd-primary-button" type="submit" disabled={done||!value.trim()}>Responder</button><button className="fd-outline-button" type="button" disabled={done} onClick={()=>{setReveal(true);finish(found);}}><Eye size={16}/>Terminar y revelar</button></form><p role="status">{feedback}</p>{done?<p className="fd-settings-message">Ronda terminada: {found.length} casillas encontradas. Repasa la fuente y comienza otra ronda.</p>:null}<p className="fd-study-source">Fuente: {subject.source} · {subject.board.source}</p></div>;}
