import test from 'node:test';import assert from 'node:assert/strict';
import {parseFolderId,validateUpload,normalizeSubfolder,validUploadSession,uploadedOffset} from '../../src/lib/drive/validation.ts';
test('carpetas Drive: ID y URLs genuinas',()=>{assert.equal(parseFolderId('https://drive.google.com/drive/u/0/folders/abcdefghijkl?usp=sharing'),'abcdefghijkl');assert.equal(parseFolderId('abcdefghijk_l-m'),'abcdefghijk_l-m');});
test('rechaza otros hosts, credenciales, puertos e IDs inválidos',()=>{for(const url of ['https://drive.google.com.evil.com/drive/folders/abcdefghijk','https://a:b@drive.google.com/drive/folders/abcdefghijk','https://drive.google.com:444/folders/abcdefghijk','123','http://localhost'])assert.throws(()=>parseFolderId(url));});
test('categoría y formato de archivo validados por el servidor',()=>{assert.equal(validateUpload({category:'catedras',fileName:'audio.MP3',size:42,contentType:'text/html'}).contentType,'audio/mpeg');for(const fileName of ['a.html','a.svg','a.exe','a.zip'])assert.throws(()=>validateUpload({category:'bitacora',fileName,size:10}));assert.throws(()=>validateUpload({category:'__proto__',fileName:'x.jpg',size:10}));});
test('tamaño positivo, entero y límite por sección',()=>{for(const size of [0,-1,1.5,Infinity,101*1024**2])assert.throws(()=>validateUpload({category:'biblioteca',fileName:'a.pdf',size}));assert.equal(validateUpload({category:'catedras',fileName:'a.mp4',size:512*1024**2}).size,512*1024**2);});
test('subcarpetas sin recorrido y con profundidad limitada',()=>{assert.deepEqual(normalizeSubfolder('../../1121/2026/10/more'),['1121','2026']);assert.ok(normalizeSubfolder('a/b/c/d/e').length<=4);});
test('sólo sesiones HTTPS reales en el endpoint de subida',()=>{assert.ok(validUploadSession('https://www.googleapis.com/upload/drive/v3/files?uploadType=resumable&upload_id=123'));for(const url of ['https://evil.com/upload/drive/v3/files','https://www.googleapis.com.evil.com/upload/drive/v3/files','http://www.googleapis.com/upload/drive/v3/files','https://www.googleapis.com/drive/v3/files'])assert.equal(validUploadSession(url),false);});
test('confirmación de bloques a partir de Range',()=>{assert.equal(uploadedOffset('bytes=0-8388607'),8388608);assert.equal(uploadedOffset(null),0);assert.equal(uploadedOffset('wrong'),0);});
