import test from 'node:test';import assert from 'node:assert/strict';
import {DEFAULT_NEWS_SOURCES,mergeSettings,assertSourceUrl,safePublicUrl,safeImageUrl} from '../../src/lib/news/sources.ts';
import {parseFeed,parseOfficialHtml,plainText} from '../../src/lib/news/parser.ts';
const source=DEFAULT_NEWS_SOURCES.find(s=>s.id==='gaceta')!;
test('RSS2: título, fecha, fuente y resumen sin HTML',()=>{const rows=parseFeed('<rss><channel><item><title>Un aviso de Derecho</title><link>https://www.gaceta.unam.mx/nota/</link><pubDate>Mon, 05 Oct 2026 12:00:00 GMT</pubDate><description><![CDATA[<p>Un resumen &amp; una referencia.</p><script>alert(1)</script>]]></description></item></channel></rss>',source);assert.equal(rows.length,1);assert.equal(rows[0].publishedAt,'2026-10-05T12:00:00.000Z');assert.equal(rows[0].summary,'Un resumen & una referencia.');});
test('Atom: enlace alternate y fecha publicada',()=>{const rows=parseFeed('<feed><entry><title>Una noticia de Derecho</title><link href="https://www.gaceta.unam.mx/nota/" rel="alternate"/><published>2026-10-05T12:00:00Z</published></entry></feed>',source);assert.equal(rows.length,1);assert.equal(rows[0].sourceUrl,'https://www.gaceta.unam.mx/nota/');});
test('no inventar una fecha de publicación a partir de la lectura',()=>{const r=parseFeed('<rss><channel><item><title>Fecha desconocida</title><link>https://www.gaceta.unam.mx/nota/</link></item></channel></rss>',source);assert.equal(r[0].publishedAt,null);});
test('no aceptar DTD/entidades externas ni HTML disfrazado de feed',()=>{assert.throws(()=>parseFeed('<!DOCTYPE xml><rss/>',source));assert.throws(()=>parseFeed('<html>Login</html>',source));});
test('descarta enlaces a otros hosts y esquemas peligrosos',()=>{const r=parseFeed('<rss><item><title>Artículo peligroso</title><link>javascript:alert(1)</link></item><item><title>Artículo ajeno</title><link>https://evil.com/</link></item></rss>',source);assert.equal(r.length,0);});
test('acotación de extractos y deduplicación',()=>{const block='<item><title>Una nota original de Derecho</title><link>https://www.gaceta.unam.mx/nota/</link><description>'+('texto '.repeat(500))+'</description></item>';const r=parseFeed('<rss>'+block+block+'</rss>',source);assert.equal(r.length,1);assert.ok(r[0].summary.length<=180);});
test('adaptador HTML conserva títulos oficiales sin inventar el año',()=>{const s=DEFAULT_NEWS_SOURCES.find(s=>s.id==='facultad')!;const r=parseOfficialHtml('<main><h3>Presentación del libro sobre Derecho</h3><p>8 octubre</p></main>',s);assert.equal(r.length,1);assert.equal(r[0].eventDate,null);assert.equal(r[0].publishedAt,null);});
test('adaptador informa páginas que requieren JS en vez de afirmar que no hay avisos',()=>assert.throws(()=>parseOfficialHtml('<div id="app"></div>',DEFAULT_NEWS_SOURCES[0]),/Sin titulares/));
test('configuración RSS no permite SSRF ni confundir configurador con feed',()=>{for(const url of ['http://127.0.0.1','https://169.254.169.254','https://dof.gob.mx.evil.com/feed','https://dof.gob.mx/website/filtroRss.php'])assert.throws(()=>assertSourceUrl(url,['dof.gob.mx']));assert.throws(()=>mergeSettings({intervalMinutes:1}));});
test('no se aceptan URLs ejecutables ni fotos de hosts ajenos',()=>{assert.equal(safePublicUrl('javascript:alert(1)'),null);assert.equal(safePublicUrl('https://127.0.0.1/x'),null);assert.equal(safeImageUrl('https://tracker.test/photo.jpg',source.url),null);assert.equal(safeImageUrl('/wp-content/p.jpg',source.url),'https://www.gaceta.unam.mx/wp-content/p.jpg');});
test('texto de feeds es texto, no código ejecutable',()=>{assert.equal(plainText('<b>Derecho</b> &lt;img onerror=alert(1)&gt;'),'Derecho <img onerror=alert(1)>');assert.doesNotThrow(()=>plainText('&#x110000;'));});

// Regressions found in the final review of the live-source adapters.
test('URL de imagen vacía no se convierte en la página de la fuente',()=>{assert.equal(safeImageUrl('',source.url),null);assert.equal(safeImageUrl('  ',source.url),null);});
test('adaptador HTML sin palabras clave sí acepta titulares',()=>{const rows=parseOfficialHtml('<main><h3><a href="/una-nota/">Un titular académico suficientemente largo</a></h3></main>',{...source,keywords:[]});assert.equal(rows.length,1);assert.equal(rows[0].sourceUrl,'https://www.gaceta.unam.mx/una-nota/');});
test('no atribuir a un evento una imagen de la tarjeta siguiente',()=>{const rows=parseOfficialHtml('<h3>Presentación de un libro sobre Derecho</h3><img src="/otro-evento.jpg"><h3>Presentación de un segundo libro sobre Derecho</h3>',DEFAULT_NEWS_SOURCES.find(s=>s.id==='facultad')!);assert.equal(rows[0].imageUrl,undefined);});
