import { createServerFn } from '@tanstack/react-start';
import { z } from 'zod';
import { authMiddleware } from '@/lib/auth/middleware';
import { getSql } from '@/lib/db';
import { parseFolderId } from './validation';
export type DriveStatus={configured:boolean;authorized:boolean;folderId:string;credentialMode:string;message:string;folderName?:string;folderSource?:string;environment?:string;branch?:string;missing?:string[];confirmed?:number;pending?:number;visibleRootItems?:number;moreRootItems?:boolean;recent?:{file_name:string;category:string;drive_file_id:string;verified_at:string}[]};
export const loadDriveStatus=createServerFn({method:'GET'}).middleware([authMiddleware]).handler(async({context}):Promise<DriveStatus>=>{const{requireMemberId}=await import('@/lib/access.server');await requireMemberId(context.userId,true);const{driveDiagnostics}=await import('./diagnostics.server');return driveDiagnostics(false);});
export const testDriveConnection=createServerFn({method:'POST'}).middleware([authMiddleware]).handler(async({context}):Promise<DriveStatus>=>{const{requireMemberId}=await import('@/lib/access.server');await requireMemberId(context.userId,true);const{driveDiagnostics}=await import('./diagnostics.server');return driveDiagnostics(true);});
export const saveDriveFolder=createServerFn({method:'POST'}).middleware([authMiddleware]).validator(z.object({folder:z.string().min(10).max(500)})).handler(async({context,data})=>{const{requireMemberId}=await import('@/lib/access.server');await requireMemberId(context.userId,true);const id=parseFolderId(data.folder);const{folderInfo}=await import('./service.server');await folderInfo(id);const sql=await getSql();await sql`insert into app_settings(setting_key,setting_value,updated_by) values('google_drive_folder_id',${id},${context.userId}) on conflict(setting_key) do update set setting_value=excluded.setting_value,updated_by=excluded.updated_by,updated_at=now()`;return {ok:true};});
