import {useEffect,useRef,useState} from 'react';
import {Camera,Trash2} from 'lucide-react';
export function FoodPhotoInput({existingUrl,editMode=false}:{existingUrl?:string|null;editMode?:boolean}){
 const input=useRef<HTMLInputElement>(null);const[file,setFile]=useState<File|null>(null),[preview,setPreview]=useState(''),[error,setError]=useState('');
 useEffect(()=>{if(!file){setPreview('');return;}const url=URL.createObjectURL(file);setPreview(url);return()=>URL.revokeObjectURL(url);},[file]);
 useEffect(()=>{const form=input.current?.form;const reset=()=>{setFile(null);setError('');};form?.addEventListener('reset',reset);return()=>form?.removeEventListener('reset',reset);},[]);
 function selected(){const f=input.current?.files?.[0];setError('');if(!f){setFile(null);return;}if(!['image/jpeg','image/png','image/webp'].includes(f.type)||f.size===0||f.size>15*1024*1024){setError('Elige una imagen JPG, PNG o WEBP de hasta 15 MB, no vacía.');if(input.current)input.current.value='';setFile(null);return;}setFile(f);}
 return <fieldset className="fd-food-photo"><legend><Camera size={18}/>{editMode?'Reemplazar foto del alimento o servicio':'Foto del alimento o servicio'}</legend><p>JPG, PNG o WEBP · hasta 15 MB. La foto se envía a Drive al publicar; seleccionarla todavía no la sube.</p><input ref={input} name="photo" type="file" accept="image/jpeg,image/png,image/webp" aria-label="Seleccionar foto del alimento" onChange={selected}/>{preview||existingUrl?<figure><img src={preview||existingUrl!} alt={file?'Vista previa de la foto seleccionada':'Foto actual de la publicación'}/><figcaption>{file?file.name:'Foto actual: se conserva si no seleccionas otra.'}</figcaption></figure>:<div className="fd-food-photo-empty"><Camera size={30}/><span>Selecciona una foto para verla antes de publicar</span></div>}{file?<button type="button" className="fd-outline-button" onClick={()=>{if(input.current)input.current.value='';setFile(null);}}><Trash2 size={15}/>Quitar selección</button>:null}{error?<p className="fd-alert" role="alert">{error}</p>:null}</fieldset>;
}
