import { useQuery } from "@tanstack/react-query";
import { useEffect, useState } from "react";
import { Link } from "@tanstack/react-router";
import { ArrowUpRight, Bookmark, CalendarDays, CheckCircle2, Newspaper, Play, Radio, RefreshCw, Scale, GraduationCap, AlertCircle } from "lucide-react";
import { NewsArt } from "./news-art";
import { coverUrl,recentItem } from "@/lib/news/media";
import { loadNews } from "@/lib/news/functions";
import { NEWS_CATEGORIES, type NewsItem } from "@/lib/news/types";
import { NEWS_SNAPSHOT, SNAPSHOT_VERIFIED_AT } from "@/lib/news/snapshot";
import { DEFAULT_NEWS_SOURCES } from "@/lib/news/sources";
import { useCurrentUserState } from "@/lib/auth/use-current-user";
export const newsQuery={queryKey:["news-v7"],queryFn:()=>loadNews(),staleTime:60_000,retry:1};
export const displayDate=(value:string)=>new Intl.DateTimeFormat("es-MX",{day:"numeric",month:"short",year:"numeric",timeZone:"America/Mexico_City"}).format(new Date(value.length===10?`${value}T12:00:00-06:00`:value));
function useSavedNews(){const{user}=useCurrentUserState();const key=`fd-saved-news:${user?.id??"visitante"}`;const[saved,setSaved]=useState<string[]>([]);useEffect(()=>{try{const data=JSON.parse(localStorage.getItem(key)??"[]");setSaved(Array.isArray(data)?data.filter((x:unknown)=>typeof x==="string"):[]);}catch{setSaved([]);}},[key]);function toggle(id:string){setSaved(list=>{const next=list.includes(id)?list.filter(x=>x!==id):[...list,id].slice(-500);try{localStorage.setItem(key,JSON.stringify(next));}catch{}return next;});}return{saved,toggle};}
export function NewsCard({item,featured=false,saved,onSave}:{item:NewsItem;featured?:boolean;saved:boolean;onSave:()=>void}){
 const[badImage,setBadImage]=useState(false);const[play,setPlay]=useState(false);const cover=coverUrl(item);const image=!!cover&&!badImage;
 useEffect(()=>{setBadImage(false);setPlay(false);},[item.imageUrl,item.youtubeId,item.videoUrl]);
 const Icon=item.category==="Universidad Abierta"?GraduationCap:item.category==="Legislación"||item.category==="Justicia"?Scale:Newspaper;
 const old=!!item.publishedAt&&Date.now()-new Date(item.publishedAt).getTime()>90*86400000;
 return <article className={`fd-news-card ${featured?"featured":""}`}>
  <div className={`fd-news-art cat-${item.category==="Universidad Abierta"?"dua":item.category==="Legislación"?"law":"campus"}`}>
   {image?<img src={cover!} alt={item.title} loading="lazy" decoding="async" referrerPolicy="no-referrer" onError={()=>setBadImage(true)}/>:<NewsArt category={item.category}/>}
   <span className="fd-media-label">{!image?"Ilustración de referencia":item.youtubeId&&!item.imageUrl?"Miniatura de video":"Imagen de la fuente"}</span>
   <span className="fd-news-stage">{item.youtubeId||item.videoUrl?"Video · ":""}{item.legalStage}</span><button className={`fd-save-button ${saved?"saved":""}`} onClick={onSave} aria-label={saved?"Quitar de guardados":"Guardar noticia en este navegador"} aria-pressed={saved}><Bookmark size={17} fill={saved?"currentColor":"none"}/></button>
   {item.videoUrl||item.youtubeId?<button className="fd-play-button" onClick={()=>setPlay(!play)} aria-label={play?"Cerrar video":"Reproducir video"} aria-expanded={play}><Play size={22}/></button>:null}
  </div>
  {play&&item.videoUrl?<video className="fd-news-video" src={item.videoUrl} controls playsInline preload="metadata"/>:play&&item.youtubeId?<iframe className="fd-news-video" src={`https://www.youtube-nocookie.com/embed/${item.youtubeId}`} title={`Video: ${item.title}`} allow="fullscreen; picture-in-picture" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen/>:null}
  <div className="fd-news-copy"><div className="fd-news-meta"><span>{item.sourceName}</span>{old?<b>Archivo</b>:null}</div><h3><a href={item.sourceUrl} target="_blank" rel="noopener noreferrer">{item.title}</a></h3>{item.summary?<p>{item.summary}</p>:<p>Consulta el contenido, los detalles y cualquier actualización en la fuente original.</p>}<div className="fd-news-bottom"><span><CalendarDays size={13}/>{item.publishedAt?displayDate(item.publishedAt):item.eventDate?`Evento · ${displayDate(item.eventDate)}`:"Fecha no informada"}</span><a href={item.sourceUrl} target="_blank" rel="noopener noreferrer" aria-label={`Abrir fuente: ${item.title}`}><ArrowUpRight size={19}/></a></div>{item.snapshot?<p className="fd-snapshot-note">Referencia revisada el {displayDate(SNAPSHOT_VERIFIED_AT)} · No es una lectura en directo.</p>:null}{image&&item.imageCredit?<p className="fd-image-credit">{item.imageCredit}</p>:null}{play&&item.youtubeId?<p className="fd-image-credit">Al reproducir se establece una conexión con YouTube.</p>:null}</div>
 </article>;
}
export function NewsSection({full=false}:{full?:boolean}){
 const query=useQuery(newsQuery);const[category,setCategory]=useState("Todas");const[source,setSource]=useState("Todas");const[search,setSearch]=useState("");const[onlySaved,setOnlySaved]=useState(false);const[list,setList]=useState(false);const[period,setPeriod]=useState("recientes");const{saved,toggle}=useSavedNews();
 const items=query.data?.items??NEWS_SNAPSHOT;const periodItems=full&&period!=="archivo"?items.filter(i=>i.pinned||recentItem(i,Date.now(),period==="ano"?365:90)):items;const filtered=periodItems.filter(i=>(category==="Todas"||i.category===category)&&(source==="Todas"||i.sourceId===source)&&(!onlySaved||saved.includes(i.id))&&`${i.title} ${i.summary}`.toLocaleLowerCase("es").includes(search.toLocaleLowerCase("es")));
 const enabled=query.data?.sources.filter(s=>s.enabled)??[];const connected=enabled.filter(s=>s.fetchedAt&&!s.error);
 return <section className="fd-news-section" aria-label="Noticias y actualidad">
  <div className="fd-section-heading"><div><p className="fd-eyebrow">AL DÍA, CON CONTEXTO</p><h2>Lo que pasa en Derecho<span className="fd-heading-dot">.</span></h2></div>{!full?<Link to="/noticias" className="fd-text-link">Todas las noticias <ArrowUpRight size={16}/></Link>:<button className="fd-text-link" disabled={query.isFetching} onClick={()=>void query.refetch()}><RefreshCw size={16} className={query.isFetching?"fd-spin":""}/>{query.isFetching?"Consultando…":"Consultar caché"}</button>}</div>
  <div className="fd-tabs" role="group" aria-label="Filtrar noticias por tema">{["Todas",...NEWS_CATEGORIES].map(c=><button key={c} className={category===c?"active":""} onClick={()=>setCategory(c)}>{c}</button>)}</div>
  {full?<div className="fd-filter-row"><input className="fd-field" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar en titulares…" aria-label="Buscar noticias"/><select className="fd-field" value={source} onChange={e=>setSource(e.target.value)} aria-label="Filtrar por fuente"><option>Todas</option>{DEFAULT_NEWS_SOURCES.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}<option value="editorial">Publicaciones del portal</option></select><select className="fd-field" value={period} onChange={e=>setPeriod(e.target.value)} aria-label="Periodo de las noticias"><option value="recientes">Recientes · 90 días</option><option value="ano">Último año</option><option value="archivo">Todo el archivo</option></select><button className={`fd-outline-button ${onlySaved?"selected":""}`} onClick={()=>setOnlySaved(!onlySaved)} aria-pressed={onlySaved}><Bookmark size={15}/>Guardadas</button><button className="fd-outline-button" onClick={()=>setList(!list)}>{list?"Vista de tarjetas":"Vista compacta"}</button></div>:null}
  {query.isFetching&&!query.data?<p className="fd-feed-status" role="status"><RefreshCw size={14} className="fd-spin"/>Consultando fuentes; las referencias iniciales están identificadas.</p>:null}
  {query.isError||query.data?.error?<p className="fd-alert" role="status"><AlertCircle size={16}/>{query.data?.error??"No fue posible consultar las fuentes. Se muestran referencias iniciales, no noticias en directo."}</p>:null}
  <div className={`fd-news-grid ${list?"compact":""}`}>{(full?filtered:filtered.slice(0,3)).map((item,index)=><NewsCard key={item.id} item={item} featured={!full&&index===0} saved={saved.includes(item.id)} onSave={()=>toggle(item.id)}/>)}</div>
  {!filtered.length?<div className="fd-empty"><Newspaper size={28}/><h3>Sin resultados para este filtro</h3><p>Prueba otro tema, selecciona Todo el archivo o consulta las fuentes originales. No se generan titulares para llenar la sección.</p></div>:null}
  <div className="fd-feed-footer"><span><Radio size={14}/>{enabled.length?`${connected.length} de ${enabled.length} fuentes con lectura correcta`:"Estado de conexión pendiente"}</span><span>Enlaces oficiales · Fecha y origen visibles · Guardados en este navegador</span></div>
  {full?<><details className="fd-source-details"><summary>Fuentes, frecuencia y estado de lectura</summary><p>Se consulta al visitar el portal cuando vence la caché. No es un seguimiento en tiempo real. Los errores conservan la última lectura disponible. La frecuencia y los feeds se ajustan en Control.</p><div className="fd-source-list">{DEFAULT_NEWS_SOURCES.map(s=>{const status=query.data?.sources.find(v=>v.id===s.id);return <div key={s.id}><span className="fd-source-icon"><CheckCircle2 size={17}/></span><div><a href={s.homepage} target="_blank" rel="noopener noreferrer">{s.name} <ArrowUpRight size={13}/></a><p>{s.note}</p><small>{status?status.enabled?status.error?`Error: ${status.error}`:status.fetchedAt?`Última lectura correcta: ${displayDate(status.fetchedAt)}`:"Pendiente de lectura":"Desactivada":"Sin comprobar"}</small></div><b>{status?.enabled?status.kind.toUpperCase():"Opcional"}</b></div>;})}</div></details><p className="fd-legal-note">Una iniciativa, un comunicado, una publicación en el DOF y la entrada en vigor de una norma son momentos distintos. Verifica el texto oficial, sus transitorios y su ámbito de aplicación. Este portal no sustituye asesoría jurídica.</p></>:null}
 </section>;
}
