import { useQuery } from "@tanstack/react-query";
import { useEffect, useState } from "react";
import { Link } from "@tanstack/react-router";
import { ArrowUpRight, Bookmark, CalendarDays, Newspaper, Play, Radio, RefreshCw, AlertCircle, CheckCircle2 } from "lucide-react";
import { NewsArt } from "./news-art";
import { coverUrl } from "@/lib/news/media";
import { selectNews,homeNews,type NewsPeriod } from "@/lib/news/selection";
import { loadNews } from "@/lib/news/functions";
import { NEWS_CATEGORIES,type NewsItem } from "@/lib/news/types";
import { NEWS_SNAPSHOT,SNAPSHOT_VERIFIED_AT } from "@/lib/news/snapshot";
import { DEFAULT_NEWS_SOURCES } from "@/lib/news/sources";
import { useCurrentUserState } from "@/lib/auth/use-current-user";
export const newsQuery={queryKey:["news-v7"],queryFn:()=>loadNews(),staleTime:60_000,retry:1};
export const displayDate=(value:string)=>{const d=new Date(value.length===10?`${value}T12:00:00-06:00`:value);return Number.isFinite(d.getTime())?new Intl.DateTimeFormat("es-MX",{day:"numeric",month:"short",year:"numeric",timeZone:"America/Mexico_City"}).format(d):"Fecha no informada";};
function useSavedNews(){const{user}=useCurrentUserState();const key=`fd-saved-news:${user?.id??"visitante"}`;const[saved,setSaved]=useState<string[]>([]);useEffect(()=>{try{const data=JSON.parse(localStorage.getItem(key)??"[]");setSaved(Array.isArray(data)?data.filter((x:unknown)=>typeof x==="string"):[]);}catch{setSaved([]);}},[key]);function toggle(id:string){setSaved(list=>{const next=list.includes(id)?list.filter(x=>x!==id):[...list,id].slice(-500);try{localStorage.setItem(key,JSON.stringify(next));}catch{}return next;});}return{saved,toggle};}
export function NewsCard({item,featured=false,saved,onSave}:{item:NewsItem;featured?:boolean;saved:boolean;onSave:()=>void}){
 const[badImage,setBadImage]=useState(false),[play,setPlay]=useState(false);const cover=coverUrl(item),image=!!cover&&!badImage;
 const youtube=item.youtubeId&&/^[\w-]{11}$/.test(item.youtubeId)?item.youtubeId:null;
 useEffect(()=>{setBadImage(false);setPlay(false);},[item.imageUrl,item.youtubeId,item.videoUrl]);
 const old=!!item.publishedAt&&Date.now()-new Date(item.publishedAt).getTime()>90*86400000;
 return <article className={`fd-news-card ${featured?"featured":""}`}>
 <div className="fd-news-art">{image?<img src={cover!} alt={item.title} loading="lazy" decoding="async" referrerPolicy="no-referrer" onLoad={e=>{const img=e.currentTarget;if(img.naturalWidth<160||img.naturalHeight<90)setBadImage(true);}} onError={()=>setBadImage(true)}/>:<NewsArt category={item.category}/>}
 <span className="fd-media-label">{!image?"Ilustración de referencia":youtube&&!item.imageUrl?"Miniatura de video":"Imagen de la fuente"}</span><span className="fd-news-stage">{youtube||item.videoUrl?"Video · ":""}{item.category}</span><button className={`fd-save-button ${saved?"saved":""}`} onClick={onSave} aria-label={saved?"Quitar de guardados":"Guardar noticia en este navegador"} aria-pressed={saved}><Bookmark size={16} fill={saved?"currentColor":"none"}/></button>{item.videoUrl||youtube?<button className="fd-play-button" onClick={()=>setPlay(!play)} aria-label={play?"Cerrar video":"Reproducir video"} aria-expanded={play}><Play size={22}/></button>:null}</div>
 {play&&item.videoUrl?<video className="fd-news-video" src={item.videoUrl} controls playsInline preload="metadata"/>:play&&youtube?<iframe className="fd-news-video" src={`https://www.youtube-nocookie.com/embed/${youtube}`} title={`Video: ${item.title}`} allow="fullscreen; picture-in-picture" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen/>:null}
 <div className="fd-news-copy">{image?<a className="fd-image-full" href={cover!} target="_blank" rel="noopener noreferrer">Ver imagen completa ↗</a>:null}<div className="fd-news-meta"><span>{item.sourceName}</span>{old?<b>Archivo</b>:null}</div><h3><a href={item.sourceUrl} target="_blank" rel="noopener noreferrer">{item.title}</a></h3><p>{item.summary||"Consulta los detalles y las actualizaciones en la fuente original."}</p><div className="fd-news-bottom"><span><CalendarDays size={13}/>{item.publishedAt?displayDate(item.publishedAt):item.eventDate?`Evento · ${displayDate(item.eventDate)}`:"Fecha no informada"}</span><a href={item.sourceUrl} target="_blank" rel="noopener noreferrer" aria-label={`Leer más: ${item.title}`}>Leer más <ArrowUpRight size={15}/></a></div>{item.legalStage!=="Información"?<small className="fd-news-kind">{item.legalStage}</small>:null}{item.snapshot?<p className="fd-snapshot-note">Referencia revisada el {displayDate(SNAPSHOT_VERIFIED_AT)} · No es una lectura en directo.</p>:null}{image&&item.imageCredit?<p className="fd-image-credit">{item.imageCredit}</p>:null}{play&&youtube?<p className="fd-image-credit">Al reproducir se establece una conexión con YouTube.</p>:null}</div></article>;
}
export function NewsSection({full=false}:{full?:boolean}){
 const query=useQuery(newsQuery);const[category,setCategory]=useState("Todas"),[source,setSource]=useState("Todas"),[search,setSearch]=useState(""),[onlySaved,setOnlySaved]=useState(false),[list,setList]=useState(false),[period,setPeriod]=useState<NewsPeriod>("archivo"),[limit,setLimit]=useState(12);const{saved,toggle}=useSavedNews();
 const items=query.data?.items??NEWS_SNAPSHOT;
 const filtered=selectNews(items,{category,source,search,period,saved:onlySaved?saved:undefined});
 const visible=full?filtered.slice(0,limit):homeNews(filtered);
 const enabled=query.data?.sources.filter(s=>s.enabled)??[];const connected=enabled.filter(s=>s.fetchedAt&&!s.error);
 useEffect(()=>setLimit(12),[category,source,search,period,onlySaved]);
 function reset(){setCategory("Todas");setSource("Todas");setSearch("");setOnlySaved(false);setPeriod("archivo");setLimit(12);}
 return <section className={`fd-news-section ${full?"fd-news-full":""}`} aria-label="Noticias y actualidad"><div className="fd-section-heading"><div><p className="fd-eyebrow">AL DÍA, CON CONTEXTO</p><h2>{full?"Lo que pasa en Derecho.":"Noticias y actualidad"}</h2></div>{!full?<Link to="/noticias" className="fd-text-link">Ver todas <ArrowUpRight size={16}/></Link>:<button className="fd-text-link" disabled={query.isFetching} onClick={()=>void query.refetch()}><RefreshCw size={16} className={query.isFetching?"fd-spin":""}/>{query.isFetching?"Consultando…":"Actualizar vista"}</button>}</div>
 {full?<><div className="fd-tabs" role="group" aria-label="Filtrar noticias por tema">{["Todas",...NEWS_CATEGORIES].map(c=><button key={c} aria-pressed={category===c} className={category===c?"active":""} onClick={()=>setCategory(c)}>{c}<small>{c==="Todas"?items.length:items.filter(i=>i.category===c).length}</small></button>)}</div><div className="fd-filter-row"><input className="fd-field" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar en titulares, fuentes o temas…" aria-label="Buscar noticias"/><select className="fd-field" value={source} onChange={e=>setSource(e.target.value)} aria-label="Filtrar por fuente"><option value="Todas">Todas las fuentes</option>{DEFAULT_NEWS_SOURCES.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}<option value="editorial">Publicaciones del portal</option></select><select className="fd-field" value={period} onChange={e=>setPeriod(e.target.value as NewsPeriod)} aria-label="Periodo de las noticias"><option value="archivo">Todas las fechas</option><option value="recientes">Últimos 90 días</option><option value="ano">Último año</option><option value="sin-fecha">Fecha no informada</option></select><button className={`fd-outline-button ${onlySaved?"selected":""}`} onClick={()=>setOnlySaved(!onlySaved)} aria-pressed={onlySaved}><Bookmark size={15}/>Guardadas</button><button className="fd-outline-button" onClick={()=>setList(!list)}>{list?"Tarjetas":"Vista compacta"}</button></div><div className="fd-news-result-line"><p role="status">{filtered.length} publicaciones disponibles{period==="archivo"?" · Incluye archivo y avisos sin fecha; no todos son noticias recientes.":" para estos filtros."}</p><button onClick={reset}>Limpiar filtros</button></div></>:null}
 {query.isFetching&&!query.data?<p className="fd-feed-status" role="status"><RefreshCw size={14} className="fd-spin"/>Consultando fuentes; las referencias iniciales están identificadas.</p>:null}
 {query.isError||query.data?.error?<p className="fd-alert" role="status"><AlertCircle size={16}/>{query.data?.error??"No fue posible consultar las fuentes. Se muestran referencias iniciales, no noticias en directo."}</p>:null}
 <div className={`fd-news-grid ${list?"compact":""}`}>{visible.map(item=><NewsCard key={item.id} item={item} saved={saved.includes(item.id)} onSave={()=>toggle(item.id)}/>)}</div>
 {!filtered.length?<div className="fd-empty"><Newspaper size={28}/><h3>No hay publicaciones con estos filtros</h3><p>Las entradas antiguas y los avisos sin fecha no aparecen al elegir un periodo reciente.</p><button className="fd-primary-button" onClick={reset}>Mostrar todas las publicaciones</button></div>:null}
 {full&&limit<filtered.length?<button className="fd-news-more fd-outline-button" onClick={()=>setLimit(v=>v+12)}>Mostrar más ({filtered.length-limit} restantes)</button>:null}
 <div className="fd-feed-footer"><span><Radio size={14}/>{enabled.length?`${connected.length} de ${enabled.length} fuentes con lectura correcta`:"Estado de conexión pendiente"}</span><span>Fecha y fuente originales · Sin titulares inventados</span></div>
 {full?<><div className="fd-source-shortcuts"><h3>Fuentes a un clic</h3><div>{DEFAULT_NEWS_SOURCES.filter(s=>["dua","facultad","gaceta-actualidad","dof"].includes(s.id)).map(s=><a key={s.id} href={s.homepage} target="_blank" rel="noopener noreferrer">{s.name}<ArrowUpRight size={16}/></a>)}</div><p>Acceso directo a los sitios originales, incluso cuando el lector no puede extraer sus avisos.</p></div><details className="fd-source-details"><summary>Fuentes, frecuencia y estado de lectura</summary><p>La consulta se renueva al visitar el portal cuando vence la caché. Actualizar vista no fuerza a los sitios de origen; moderación puede usar Guardar y probar en Control.</p><div className="fd-source-list">{DEFAULT_NEWS_SOURCES.map(s=>{const status=query.data?.sources.find(v=>v.id===s.id);const ok=!!status?.fetchedAt&&!status.error;return <div key={s.id}><span className="fd-source-icon">{ok?<CheckCircle2 size={17}/>:<AlertCircle size={17}/>}</span><div><a href={s.homepage} target="_blank" rel="noopener noreferrer">{s.name} <ArrowUpRight size={13}/></a><p>{s.note}</p><small>{status?status.enabled?status.error?`Error: ${status.error}`:status.fetchedAt?`${status.count} entradas · Lectura correcta: ${displayDate(status.fetchedAt)}`:"Pendiente de lectura":"Desactivada":"Sin comprobar"}</small></div><b>{status?.enabled?status.kind.toUpperCase():"Opcional"}</b></div>;})}</div></details><p className="fd-legal-note">Una iniciativa, un comunicado, una publicación en el DOF y la entrada en vigor de una norma son momentos distintos. Consulta el texto oficial y sus transitorios. Los ensayos académicos no son resoluciones judiciales.</p></>:null}</section>;
}
