import { useMemo, useState } from "react";
import { BarChart3, TrendingUp, Info } from "lucide-react";
import { analyzeAvailability } from "@/lib/polls/analytics";
import type { ActivityPoll } from "@/lib/votaciones";
import { formatLongDate,getTodayIso } from "@/lib/format";
export function PollInsights({poll}:{poll:ActivityPoll}){
 const a=useMemo(()=>analyzeAvailability(poll.responses,getTodayIso()),[poll.responses]);const[history,setHistory]=useState(false);
 const lead=a.leaders.length===1?a.leaders[0]:null;const circumference=2*Math.PI*45;let offset=0;
 const scheduled=poll.scheduledDate||poll.eventDate;const scheduledTime=poll.scheduledTime||poll.eventTime;
 return <section className="fd-poll-insights" aria-label="Distribución y tendencia de disponibilidad">
  <div className="fd-insight-title"><div><p className="fd-eyebrow">RESPUESTAS REALES · SIN DOBLE CONTEO</p><h3><BarChart3 size={22}/>Así se está repartiendo el grupo</h3></div><span className="fd-state"><b>{a.total}</b> participantes</span></div>
  {scheduled?<p className="fd-scheduled"><strong>Fecha calendarizada:</strong> {formatLongDate(scheduled)}{scheduledTime?` · ${scheduledTime}`:""}. La tendencia de las respuestas no modifica este acuerdo automáticamente.</p>:null}
  <div className="fd-poll-charts"><figure><figcaption>Cómo respondieron</figcaption><div className="fd-donut-wrap"><svg viewBox="0 0 120 120" role="img" aria-label={a.modes.map(m=>`${m.label}: ${m.count}`).join(". ")}><circle cx="60" cy="60" r="45" fill="none" stroke="var(--color-line)" strokeWidth="11"/>{a.modes.map((m,i)=>{const size=a.total?m.count/a.total*circumference:0;const start=offset;offset+=size;return <circle key={m.label} className={`fd-segment-${i}`} cx="60" cy="60" r="45" fill="none" strokeWidth="11" strokeDasharray={`${size} ${circumference-size}`} strokeDashoffset={-start} transform="rotate(-90 60 60)"/>;})}<text x="60" y="59" textAnchor="middle" className="fd-donut-total">{a.total}</text><text x="60" y="76" textAnchor="middle" className="fd-donut-label">PERSONAS</text></svg><div className="fd-donut-legend">{a.modes.map((m,i)=><p key={m.label}><i className={`fd-key-${i}`}/><span>{m.label}</span><b>{m.count}</b><small>{a.total?Math.round(m.count/a.total*100):0}%</small></p>)}</div></div><p className="fd-chart-note">Porcentajes redondeados. Cada registro aparece en un solo modo.</p></figure>
  <figure><figcaption>Días mencionados</figcaption><div className="fd-bars">{a.days.map(d=><div key={d.day}><span>{d.label}</span><div className="fd-bar-track"><i style={{width:`${a.total?d.count/a.total*100:0}%`}}/></div><b>{d.count}</b></div>)}</div><p className="fd-chart-note">Una persona puede elegir varios días. Los {a.flexible} “Me adapto” no se convierten en votos para cada día. Incluye respuestas históricas.</p></figure></div>
  <div className="fd-poll-trend"><TrendingUp size={25}/><div><p className="fd-eyebrow">ORIENTACIÓN ACTUAL · NO ES UNA DECISIÓN FINAL</p><h4>{!a.total?"Todavía no hay respuestas":a.leaders.length>1?`Empate entre ${a.leaders.length} propuestas futuras`:lead?`${formatLongDate(lead.date)} · ${lead.time}`:a.leadingDays.length===1?`Se inclina hacia ${a.leadingDays[0].label.toLowerCase()}`:a.leadingDays.length>1?`Empate de días: ${a.leadingDays.map(d=>d.label).join(", ")}`:"El grupo se adapta; falta proponer fecha y hora"}</h4><p>{lead?`${lead.compatible} de ${a.total} registros potencialmente compatibles (${lead.percent}%): ${lead.exact} de fecha/hora exacta, ${lead.weekly} de disponibilidad semanal y ${lead.flexible} flexibles.`:a.leaders.length>1?"No hay una propuesta ganadora única. Los flexibles no rompen el empate.":"Falta una fecha y hora futura concreta para recomendar. No combinamos por separado el día más mencionado con la hora más mencionada."}</p><small>La organización puede fijar el acuerdo desde Editar votación. No se cambia ni se cierra una votación desde esta gráfica.</small></div></div>
  {a.slots.length?<div className="fd-poll-ranking"><div><h4>Comparación de propuestas</h4>{a.slots.some(s=>s.past)?<label><input type="checkbox" checked={history} onChange={e=>setHistory(e.target.checked)}/>Ver fechas pasadas</label>:null}</div><div className="fd-table-scroll"><table><caption>Compatibilidad por fecha y hora; una persona se cuenta una vez por opción.</caption><thead><tr><th>Propuesta</th><th>Exactas</th><th>Semanal</th><th>Flexibles</th><th>Compatibles</th></tr></thead><tbody>{(history?a.slots:a.future).map(s=><tr key={s.key} className={s.past?"fd-past-row":""}><td>{formatLongDate(s.date)} · {s.time}{s.past?<small>Pasada · no se recomienda</small>:null}</td><td>{s.exact}</td><td>{s.weekly}</td><td>{s.flexible}</td><td><b>{s.compatible}/{a.total}</b> · {s.percent}%</td></tr>)}</tbody></table></div></div>:null}
  <details className="fd-poll-method"><summary><Info size={15}/>Cómo se calcula y qué significa</summary><p>Se comparan únicamente pares de fecha y hora propuestos. Se cuenta una vez por opción a quien eligió ese par, a quien coincide por día de semana y hora, y a quien indicó Me adapto. Una preferencia semanal de otra hora no se suma. Las fechas pasadas no lideran. Compatibilidad no significa asistencia confirmada, ni es una predicción estadística.</p><p>Las horas son menciones independientes, no propuestas nuevas: {a.hours.length?a.hours.map(([hour,count])=>`${hour}: ${count}`).join(" · "):"sin horas registradas"}.</p></details>
 </section>;
}
