import type { NewsItem } from "./types.ts";
// Human-reviewed references, NOT a live feed. Never invent a publication date or infer the year of an event.
export const SNAPSHOT_VERIFIED_AT="2026-10-06";
export const NEWS_SNAPSHOT:NewsItem[]=[
 {id:"reference-dua-sua",sourceId:"dua",sourceName:"Universidad Abierta · DUA",sourceUrl:"https://duaderecho.unam.mx/",title:"Universidad Abierta: avisos y actividades de tu modalidad",summary:"Acceso a la página de la DUA. Esta referencia no anuncia un evento concreto: consulta el sitio original para confirmar avisos, fechas y actividades de tu modalidad.",category:"Universidad Abierta",legalStage:"Fuente de consulta",publishedAt:null,eventDate:null,snapshot:true},
 {id:"reference-fd-internacional",sourceId:"facultad",sourceName:"Facultad de Derecho · Agenda",sourceUrl:"https://www.derecho.unam.mx/eventos/",title:"Presentación: El nuevo derecho internacional público",summary:"La agenda institucional anuncia la presentación el 8 de octubre, a las 9:00, en el Auditorio Benito Juárez. Confirma año, programa y posibles cambios en el cartel de la fuente.",category:"Facultad",legalStage:"Evento",publishedAt:null,eventDate:null,snapshot:true},
 {id:"reference-fd-financiero",sourceId:"facultad",sourceName:"Facultad de Derecho · Agenda",sourceUrl:"https://www.derecho.unam.mx/eventos/",title:"Sistema financiero mexicano: regulación, innovación e inclusión",summary:"Ciclo anunciado para el 12 de octubre en el Aula Magna Jacinto Pallares. Consulta la agenda oficial para confirmar programa, año y acceso.",category:"Facultad",legalStage:"Evento",publishedAt:null,eventDate:null,snapshot:true},
 {id:"reference-gaceta-vitrales",sourceId:"gaceta",sourceName:"Gaceta UNAM",sourceUrl:"https://www.gaceta.unam.mx/develan-vitrales-de-narcissus-quagliata/",title:"Arte y memoria en la Antigua Escuela Nacional de Jurisprudencia",summary:"Gaceta informa sobre la develación de vitrales de Narcissus Quagliata. Nota de archivo; no es una noticia de octubre.",category:"Facultad",legalStage:"Información",publishedAt:"2026-03-26T12:00:00.000Z",eventDate:null,snapshot:true},
];
