import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {PLAN_COURSES} from '../../src/lib/study/plan.ts';
import {COURSE_STATUSES,validateProgress,summarizeProgress} from '../../src/lib/study/progress.ts';
import {analyzeAvailability,validDate,validTime,type AvailabilityInput} from '../../src/lib/polls/analytics.ts';
import {parseArticleMedia,thumbnailFromListing,youtubeId,coverUrl,recentItem,attributes} from '../../src/lib/news/media.ts';
const course=PLAN_COURSES.find(c=>c.kind==='obligatoria')!;
for(const status of COURSE_STATUSES)test(`progreso: ${status}`,()=>{const p=validateProgress({[course.id]:{status}});assert.equal(summarizeProgress(p).credits,status==='aprobada'?course.credits:0);});
test('no inventar estados ni asignaturas',()=>{assert.throws(()=>validateProgress({evil:{status:'aprobada'}}));assert.throws(()=>validateProgress({[course.id]:{status:'excelente'}}));});
test('progreso utiliza usuario de sesión y revisión optimista',()=>{const s=fs.readFileSync(new URL('../../src/lib/study/functions.ts',import.meta.url),'utf8');assert.equal((s.match(/middleware\(\[authMiddleware\]\)/g)||[]).length,2);assert.ok(s.includes('where user_id = ${context.userId}'));assert.ok(s.includes('and revision=${data.revision}'));assert.ok(!s.includes('data.userId'));});
const exact=(id:number,date='2026-10-18',time='10:30'):AvailabilityInput=>({id,availabilityMode:'specific',availableDate:date,availableTime:time,preferredWeekdays:[]});const flex=(id:number):AvailabilityInput=>({id,availabilityMode:'flexible',availableDate:null,availableTime:null,preferredWeekdays:[]});const weekly=(id:number,time:string|null):AvailabilityInput=>({id,availabilityMode:'weekdays',availableDate:null,availableTime:time,preferredWeekdays:['domingo']});
test('cero respuestas sin ganador',()=>assert.equal(analyzeAvailability([],'2026-10-06').leaders.length,0));
test('flexibles no crean votos ni candidato',()=>{const a=analyzeAvailability([flex(1),flex(2)],'2026-10-06');assert.equal(a.days.reduce((n,d)=>n+d.count,0),0);assert.equal(a.leaders.length,0);});
test('compatibilidad no duplica y respeta horarios semanales',()=>{const a=analyzeAvailability([exact(1),weekly(2,null),weekly(3,'16:00'),flex(4)],'2026-10-06');assert.equal(a.leaders[0].compatible,3);assert.equal(a.leaders[0].percent,75);});
test('flexibles no rompen un empate',()=>{const a=analyzeAvailability([exact(1),exact(2,'2026-10-19'),flex(3)],'2026-10-06');assert.equal(a.leaders.length,2);});
test('no combinar máximos independientes',()=>{const a=analyzeAvailability([exact(1,'2026-10-18','10:30'),exact(2,'2026-10-18','11:00'),exact(3,'2026-10-19','09:00'),exact(4,'2026-10-20','09:00')],'2026-10-06');assert.ok(!a.slots.some(s=>s.key==='2026-10-18 09:00'));});
test('fechas pasadas no lideran',()=>{const a=analyzeAvailability([exact(1,'2026-10-05'),exact(2,'2026-10-05'),exact(3)],'2026-10-06');assert.equal(a.leaders[0].date,'2026-10-18');});
test('deduplicación por registro y fechas válidas',()=>{assert.equal(analyzeAvailability([exact(1),exact(1)],'2026-10-06').total,1);assert.equal(validDate('2026-02-30'),false);assert.equal(validDate('2028-02-29'),true);assert.equal(validTime('24:00'),false);});
const url='https://www.gaceta.unam.mx/nota/';
test('atributos distinguen src y data-src',()=>assert.equal(attributes('<img data-src="a" src="b">').src,'b'));
test('OpenGraph respeta orden variable y entidades',()=>assert.equal(parseArticleMedia('<head><meta content="/img.jpg?a=1&amp;b=2" property="og:image"></head>',url,'Gaceta').imageUrl,'https://www.gaceta.unam.mx/img.jpg?a=1&b=2'));
test('no aceptar imágenes de host ajeno',()=>assert.equal(parseArticleMedia('<meta property="og:image" content="https://evil.test/img.jpg">',url,'Gaceta').imageUrl,undefined));
test('no convertir fecha modificada en publicada',()=>assert.equal(parseArticleMedia('<meta property="article:modified_time" content="2026-10-06">',url,'Gaceta').publishedAt,undefined));
test('video de YouTube validado',()=>{assert.equal(youtubeId('https://youtu.be/AbcDEF_1234'),'AbcDEF_1234');assert.equal(youtubeId('https://youtube.com.evil.test/embed/AbcDEF_1234'),null);assert.equal(parseArticleMedia('<article><iframe src="https://www.youtube-nocookie.com/embed/AbcDEF_1234"></iframe></article>',url,'Gaceta').youtubeId,'AbcDEF_1234');});
test('no mezclar miniatura de noticia contigua',()=>{const html='<a href="/nota/"><img data-src="/a.jpg"></a><a href="/otra/"><img src="/b.jpg"></a>';assert.equal(thumbnailFromListing(html,url,url),'https://www.gaceta.unam.mx/a.jpg');});
test('lectura acotada',()=>assert.throws(()=>parseArticleMedia('x'.repeat(2000001),url,'Gaceta')));
