/* eslint-disable */
// @ts-nocheck
// Generated route tree. TanStack regenerates this file during the next Vite build.
import { Route as rootRouteImport } from "./routes/__root";
import { Route as R0Import } from "./routes/agenda";
import { Route as R1Import } from "./routes/api/auth/$";
import { Route as R2Import } from "./routes/api/bitacora-upload";
import { Route as R3Import } from "./routes/api/catedra-upload";
import { Route as R4Import } from "./routes/api/drive-complete";
import { Route as R5Import } from "./routes/api/drive-file";
import { Route as R6Import } from "./routes/api/drive-upload";
import { Route as R7Import } from "./routes/api/library-upload";
import { Route as R8Import } from "./routes/api/media-token";
import { Route as R9Import } from "./routes/api/services-upload";
import { Route as R10Import } from "./routes/biblioteca";
import { Route as R11Import } from "./routes/bitacora";
import { Route as R12Import } from "./routes/catedras";
import { Route as R13Import } from "./routes/clases";
import { Route as R14Import } from "./routes/control";
import { Route as R15Import } from "./routes/index";
import { Route as R16Import } from "./routes/login";
import { Route as R17Import } from "./routes/mesas";
import { Route as R18Import } from "./routes/mural";
import { Route as R19Import } from "./routes/noticias";
import { Route as R20Import } from "./routes/plan-estudios";
import { Route as R21Import } from "./routes/registro";
import { Route as R22Import } from "./routes/rutas";
import { Route as R23Import } from "./routes/servicios";
import { Route as R24Import } from "./routes/tareas";
import { Route as R25Import } from "./routes/votaciones";
const R0 = R0Import.update({ id:"/agenda", path:"/agenda", getParentRoute:()=>rootRouteImport } as any);
const R1 = R1Import.update({ id:"/api/auth/$", path:"/api/auth/$", getParentRoute:()=>rootRouteImport } as any);
const R2 = R2Import.update({ id:"/api/bitacora-upload", path:"/api/bitacora-upload", getParentRoute:()=>rootRouteImport } as any);
const R3 = R3Import.update({ id:"/api/catedra-upload", path:"/api/catedra-upload", getParentRoute:()=>rootRouteImport } as any);
const R4 = R4Import.update({ id:"/api/drive-complete", path:"/api/drive-complete", getParentRoute:()=>rootRouteImport } as any);
const R5 = R5Import.update({ id:"/api/drive-file", path:"/api/drive-file", getParentRoute:()=>rootRouteImport } as any);
const R6 = R6Import.update({ id:"/api/drive-upload", path:"/api/drive-upload", getParentRoute:()=>rootRouteImport } as any);
const R7 = R7Import.update({ id:"/api/library-upload", path:"/api/library-upload", getParentRoute:()=>rootRouteImport } as any);
const R8 = R8Import.update({ id:"/api/media-token", path:"/api/media-token", getParentRoute:()=>rootRouteImport } as any);
const R9 = R9Import.update({ id:"/api/services-upload", path:"/api/services-upload", getParentRoute:()=>rootRouteImport } as any);
const R10 = R10Import.update({ id:"/biblioteca", path:"/biblioteca", getParentRoute:()=>rootRouteImport } as any);
const R11 = R11Import.update({ id:"/bitacora", path:"/bitacora", getParentRoute:()=>rootRouteImport } as any);
const R12 = R12Import.update({ id:"/catedras", path:"/catedras", getParentRoute:()=>rootRouteImport } as any);
const R13 = R13Import.update({ id:"/clases", path:"/clases", getParentRoute:()=>rootRouteImport } as any);
const R14 = R14Import.update({ id:"/control", path:"/control", getParentRoute:()=>rootRouteImport } as any);
const R15 = R15Import.update({ id:"/", path:"/", getParentRoute:()=>rootRouteImport } as any);
const R16 = R16Import.update({ id:"/login", path:"/login", getParentRoute:()=>rootRouteImport } as any);
const R17 = R17Import.update({ id:"/mesas", path:"/mesas", getParentRoute:()=>rootRouteImport } as any);
const R18 = R18Import.update({ id:"/mural", path:"/mural", getParentRoute:()=>rootRouteImport } as any);
const R19 = R19Import.update({ id:"/noticias", path:"/noticias", getParentRoute:()=>rootRouteImport } as any);
const R20 = R20Import.update({ id:"/plan-estudios", path:"/plan-estudios", getParentRoute:()=>rootRouteImport } as any);
const R21 = R21Import.update({ id:"/registro", path:"/registro", getParentRoute:()=>rootRouteImport } as any);
const R22 = R22Import.update({ id:"/rutas", path:"/rutas", getParentRoute:()=>rootRouteImport } as any);
const R23 = R23Import.update({ id:"/servicios", path:"/servicios", getParentRoute:()=>rootRouteImport } as any);
const R24 = R24Import.update({ id:"/tareas", path:"/tareas", getParentRoute:()=>rootRouteImport } as any);
const R25 = R25Import.update({ id:"/votaciones", path:"/votaciones", getParentRoute:()=>rootRouteImport } as any);
export interface FileRoutesByFullPath {
  "/agenda": typeof R0;
  "/api/auth/$": typeof R1;
  "/api/bitacora-upload": typeof R2;
  "/api/catedra-upload": typeof R3;
  "/api/drive-complete": typeof R4;
  "/api/drive-file": typeof R5;
  "/api/drive-upload": typeof R6;
  "/api/library-upload": typeof R7;
  "/api/media-token": typeof R8;
  "/api/services-upload": typeof R9;
  "/biblioteca": typeof R10;
  "/bitacora": typeof R11;
  "/catedras": typeof R12;
  "/clases": typeof R13;
  "/control": typeof R14;
  "/": typeof R15;
  "/login": typeof R16;
  "/mesas": typeof R17;
  "/mural": typeof R18;
  "/noticias": typeof R19;
  "/plan-estudios": typeof R20;
  "/registro": typeof R21;
  "/rutas": typeof R22;
  "/servicios": typeof R23;
  "/tareas": typeof R24;
  "/votaciones": typeof R25;
}
export interface FileRoutesByTo {
  "/agenda": typeof R0;
  "/api/auth/$": typeof R1;
  "/api/bitacora-upload": typeof R2;
  "/api/catedra-upload": typeof R3;
  "/api/drive-complete": typeof R4;
  "/api/drive-file": typeof R5;
  "/api/drive-upload": typeof R6;
  "/api/library-upload": typeof R7;
  "/api/media-token": typeof R8;
  "/api/services-upload": typeof R9;
  "/biblioteca": typeof R10;
  "/bitacora": typeof R11;
  "/catedras": typeof R12;
  "/clases": typeof R13;
  "/control": typeof R14;
  "/": typeof R15;
  "/login": typeof R16;
  "/mesas": typeof R17;
  "/mural": typeof R18;
  "/noticias": typeof R19;
  "/plan-estudios": typeof R20;
  "/registro": typeof R21;
  "/rutas": typeof R22;
  "/servicios": typeof R23;
  "/tareas": typeof R24;
  "/votaciones": typeof R25;
}
export interface FileRoutesById {
  "/agenda": typeof R0;
  "/api/auth/$": typeof R1;
  "/api/bitacora-upload": typeof R2;
  "/api/catedra-upload": typeof R3;
  "/api/drive-complete": typeof R4;
  "/api/drive-file": typeof R5;
  "/api/drive-upload": typeof R6;
  "/api/library-upload": typeof R7;
  "/api/media-token": typeof R8;
  "/api/services-upload": typeof R9;
  "/biblioteca": typeof R10;
  "/bitacora": typeof R11;
  "/catedras": typeof R12;
  "/clases": typeof R13;
  "/control": typeof R14;
  "/": typeof R15;
  "/login": typeof R16;
  "/mesas": typeof R17;
  "/mural": typeof R18;
  "/noticias": typeof R19;
  "/plan-estudios": typeof R20;
  "/registro": typeof R21;
  "/rutas": typeof R22;
  "/servicios": typeof R23;
  "/tareas": typeof R24;
  "/votaciones": typeof R25;
  __root__:typeof rootRouteImport;
}
export interface FileRouteTypes {fileRoutesByFullPath:FileRoutesByFullPath; fullPaths:"/agenda" | "/api/auth/$" | "/api/bitacora-upload" | "/api/catedra-upload" | "/api/drive-complete" | "/api/drive-file" | "/api/drive-upload" | "/api/library-upload" | "/api/media-token" | "/api/services-upload" | "/biblioteca" | "/bitacora" | "/catedras" | "/clases" | "/control" | "/" | "/login" | "/mesas" | "/mural" | "/noticias" | "/plan-estudios" | "/registro" | "/rutas" | "/servicios" | "/tareas" | "/votaciones";fileRoutesByTo:FileRoutesByTo;to:"/agenda" | "/api/auth/$" | "/api/bitacora-upload" | "/api/catedra-upload" | "/api/drive-complete" | "/api/drive-file" | "/api/drive-upload" | "/api/library-upload" | "/api/media-token" | "/api/services-upload" | "/biblioteca" | "/bitacora" | "/catedras" | "/clases" | "/control" | "/" | "/login" | "/mesas" | "/mural" | "/noticias" | "/plan-estudios" | "/registro" | "/rutas" | "/servicios" | "/tareas" | "/votaciones";id:"__root__" | "/agenda" | "/api/auth/$" | "/api/bitacora-upload" | "/api/catedra-upload" | "/api/drive-complete" | "/api/drive-file" | "/api/drive-upload" | "/api/library-upload" | "/api/media-token" | "/api/services-upload" | "/biblioteca" | "/bitacora" | "/catedras" | "/clases" | "/control" | "/" | "/login" | "/mesas" | "/mural" | "/noticias" | "/plan-estudios" | "/registro" | "/rutas" | "/servicios" | "/tareas" | "/votaciones";fileRoutesById:FileRoutesById;}
export interface RootRouteChildren {
R0:typeof R0;
R1:typeof R1;
R2:typeof R2;
R3:typeof R3;
R4:typeof R4;
R5:typeof R5;
R6:typeof R6;
R7:typeof R7;
R8:typeof R8;
R9:typeof R9;
R10:typeof R10;
R11:typeof R11;
R12:typeof R12;
R13:typeof R13;
R14:typeof R14;
R15:typeof R15;
R16:typeof R16;
R17:typeof R17;
R18:typeof R18;
R19:typeof R19;
R20:typeof R20;
R21:typeof R21;
R22:typeof R22;
R23:typeof R23;
R24:typeof R24;
R25:typeof R25;
}
declare module "@tanstack/react-router" { interface FileRoutesByPath {
"/agenda":{id:"/agenda";path:"/agenda";fullPath:"/agenda";preLoaderRoute:typeof R0Import;parentRoute:typeof rootRouteImport;};
"/api/auth/$":{id:"/api/auth/$";path:"/api/auth/$";fullPath:"/api/auth/$";preLoaderRoute:typeof R1Import;parentRoute:typeof rootRouteImport;};
"/api/bitacora-upload":{id:"/api/bitacora-upload";path:"/api/bitacora-upload";fullPath:"/api/bitacora-upload";preLoaderRoute:typeof R2Import;parentRoute:typeof rootRouteImport;};
"/api/catedra-upload":{id:"/api/catedra-upload";path:"/api/catedra-upload";fullPath:"/api/catedra-upload";preLoaderRoute:typeof R3Import;parentRoute:typeof rootRouteImport;};
"/api/drive-complete":{id:"/api/drive-complete";path:"/api/drive-complete";fullPath:"/api/drive-complete";preLoaderRoute:typeof R4Import;parentRoute:typeof rootRouteImport;};
"/api/drive-file":{id:"/api/drive-file";path:"/api/drive-file";fullPath:"/api/drive-file";preLoaderRoute:typeof R5Import;parentRoute:typeof rootRouteImport;};
"/api/drive-upload":{id:"/api/drive-upload";path:"/api/drive-upload";fullPath:"/api/drive-upload";preLoaderRoute:typeof R6Import;parentRoute:typeof rootRouteImport;};
"/api/library-upload":{id:"/api/library-upload";path:"/api/library-upload";fullPath:"/api/library-upload";preLoaderRoute:typeof R7Import;parentRoute:typeof rootRouteImport;};
"/api/media-token":{id:"/api/media-token";path:"/api/media-token";fullPath:"/api/media-token";preLoaderRoute:typeof R8Import;parentRoute:typeof rootRouteImport;};
"/api/services-upload":{id:"/api/services-upload";path:"/api/services-upload";fullPath:"/api/services-upload";preLoaderRoute:typeof R9Import;parentRoute:typeof rootRouteImport;};
"/biblioteca":{id:"/biblioteca";path:"/biblioteca";fullPath:"/biblioteca";preLoaderRoute:typeof R10Import;parentRoute:typeof rootRouteImport;};
"/bitacora":{id:"/bitacora";path:"/bitacora";fullPath:"/bitacora";preLoaderRoute:typeof R11Import;parentRoute:typeof rootRouteImport;};
"/catedras":{id:"/catedras";path:"/catedras";fullPath:"/catedras";preLoaderRoute:typeof R12Import;parentRoute:typeof rootRouteImport;};
"/clases":{id:"/clases";path:"/clases";fullPath:"/clases";preLoaderRoute:typeof R13Import;parentRoute:typeof rootRouteImport;};
"/control":{id:"/control";path:"/control";fullPath:"/control";preLoaderRoute:typeof R14Import;parentRoute:typeof rootRouteImport;};
"/":{id:"/";path:"/";fullPath:"/";preLoaderRoute:typeof R15Import;parentRoute:typeof rootRouteImport;};
"/login":{id:"/login";path:"/login";fullPath:"/login";preLoaderRoute:typeof R16Import;parentRoute:typeof rootRouteImport;};
"/mesas":{id:"/mesas";path:"/mesas";fullPath:"/mesas";preLoaderRoute:typeof R17Import;parentRoute:typeof rootRouteImport;};
"/mural":{id:"/mural";path:"/mural";fullPath:"/mural";preLoaderRoute:typeof R18Import;parentRoute:typeof rootRouteImport;};
"/noticias":{id:"/noticias";path:"/noticias";fullPath:"/noticias";preLoaderRoute:typeof R19Import;parentRoute:typeof rootRouteImport;};
"/plan-estudios":{id:"/plan-estudios";path:"/plan-estudios";fullPath:"/plan-estudios";preLoaderRoute:typeof R20Import;parentRoute:typeof rootRouteImport;};
"/registro":{id:"/registro";path:"/registro";fullPath:"/registro";preLoaderRoute:typeof R21Import;parentRoute:typeof rootRouteImport;};
"/rutas":{id:"/rutas";path:"/rutas";fullPath:"/rutas";preLoaderRoute:typeof R22Import;parentRoute:typeof rootRouteImport;};
"/servicios":{id:"/servicios";path:"/servicios";fullPath:"/servicios";preLoaderRoute:typeof R23Import;parentRoute:typeof rootRouteImport;};
"/tareas":{id:"/tareas";path:"/tareas";fullPath:"/tareas";preLoaderRoute:typeof R24Import;parentRoute:typeof rootRouteImport;};
"/votaciones":{id:"/votaciones";path:"/votaciones";fullPath:"/votaciones";preLoaderRoute:typeof R25Import;parentRoute:typeof rootRouteImport;};
}}
const rootRouteChildren:RootRouteChildren={R0,R1,R2,R3,R4,R5,R6,R7,R8,R9,R10,R11,R12,R13,R14,R15,R16,R17,R18,R19,R20,R21,R22,R23,R24,R25};
export const routeTree=rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>();
import type { getRouter } from "./router.tsx";
declare module "@tanstack/react-start" {interface Register {ssr:true;router:Awaited<ReturnType<typeof getRouter>>;}}
