/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as BibliotecaRouteImport } from './routes/biblioteca'
import { Route as BitacoraRouteImport } from './routes/bitacora'
import { Route as CatedrasRouteImport } from './routes/catedras'
import { Route as ClasesRouteImport } from './routes/clases'
import { Route as ControlRouteImport } from './routes/control'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MesasRouteImport } from './routes/mesas'
import { Route as MuralRouteImport } from './routes/mural'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as RutasRouteImport } from './routes/rutas'
import { Route as ServiciosRouteImport } from './routes/servicios'
import { Route as ApiMediaTokenRouteImport } from './routes/api/media-token'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaRoute = BibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => rootRouteImport,
} as any)
const BitacoraRoute = BitacoraRouteImport.update({
  id: '/bitacora',
  path: '/bitacora',
  getParentRoute: () => rootRouteImport,
} as any)
const CatedrasRoute = CatedrasRouteImport.update({
  id: '/catedras',
  path: '/catedras',
  getParentRoute: () => rootRouteImport,
} as any)
const ClasesRoute = ClasesRouteImport.update({
  id: '/clases',
  path: '/clases',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlRoute = ControlRouteImport.update({
  id: '/control',
  path: '/control',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MesasRoute = MesasRouteImport.update({
  id: '/mesas',
  path: '/mesas',
  getParentRoute: () => rootRouteImport,
} as any)
const MuralRoute = MuralRouteImport.update({
  id: '/mural',
  path: '/mural',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const RutasRoute = RutasRouteImport.update({
  id: '/rutas',
  path: '/rutas',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosRoute = ServiciosRouteImport.update({
  id: '/servicios',
  path: '/servicios',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaTokenRoute = ApiMediaTokenRouteImport.update({
  id: '/api/media-token',
  path: '/api/media-token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/biblioteca': typeof BibliotecaRoute
  '/bitacora': typeof BitacoraRoute
  '/catedras': typeof CatedrasRoute
  '/clases': typeof ClasesRoute
  '/control': typeof ControlRoute
  '/login': typeof LoginRoute
  '/mesas': typeof MesasRoute
  '/mural': typeof MuralRoute
  '/registro': typeof RegistroRoute
  '/rutas': typeof RutasRoute
  '/servicios': typeof ServiciosRoute
  '/api/media-token': typeof ApiMediaTokenRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/biblioteca': typeof BibliotecaRoute
  '/bitacora': typeof BitacoraRoute
  '/catedras': typeof CatedrasRoute
  '/clases': typeof ClasesRoute
  '/control': typeof ControlRoute
  '/login': typeof LoginRoute
  '/mesas': typeof MesasRoute
  '/mural': typeof MuralRoute
  '/registro': typeof RegistroRoute
  '/rutas': typeof RutasRoute
  '/servicios': typeof ServiciosRoute
  '/api/media-token': typeof ApiMediaTokenRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/biblioteca': typeof BibliotecaRoute
  '/bitacora': typeof BitacoraRoute
  '/catedras': typeof CatedrasRoute
  '/clases': typeof ClasesRoute
  '/control': typeof ControlRoute
  '/login': typeof LoginRoute
  '/mesas': typeof MesasRoute
  '/mural': typeof MuralRoute
  '/registro': typeof RegistroRoute
  '/rutas': typeof RutasRoute
  '/servicios': typeof ServiciosRoute
  '/api/media-token': typeof ApiMediaTokenRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/biblioteca'
    | '/bitacora'
    | '/catedras'
    | '/clases'
    | '/control'
    | '/login'
    | '/mesas'
    | '/mural'
    | '/registro'
    | '/rutas'
    | '/servicios'
    | '/api/media-token'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/biblioteca'
    | '/bitacora'
    | '/catedras'
    | '/clases'
    | '/control'
    | '/login'
    | '/mesas'
    | '/mural'
    | '/registro'
    | '/rutas'
    | '/servicios'
    | '/api/media-token'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/biblioteca'
    | '/bitacora'
    | '/catedras'
    | '/clases'
    | '/control'
    | '/login'
    | '/mesas'
    | '/mural'
    | '/registro'
    | '/rutas'
    | '/servicios'
    | '/api/media-token'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  BibliotecaRoute: typeof BibliotecaRoute
  BitacoraRoute: typeof BitacoraRoute
  CatedrasRoute: typeof CatedrasRoute
  ClasesRoute: typeof ClasesRoute
  ControlRoute: typeof ControlRoute
  LoginRoute: typeof LoginRoute
  MesasRoute: typeof MesasRoute
  MuralRoute: typeof MuralRoute
  RegistroRoute: typeof RegistroRoute
  RutasRoute: typeof RutasRoute
  ServiciosRoute: typeof ServiciosRoute
  ApiMediaTokenRoute: typeof ApiMediaTokenRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca': {
      id: '/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof BibliotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bitacora': {
      id: '/bitacora'
      path: '/bitacora'
      fullPath: '/bitacora'
      preLoaderRoute: typeof BitacoraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catedras': {
      id: '/catedras'
      path: '/catedras'
      fullPath: '/catedras'
      preLoaderRoute: typeof CatedrasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clases': {
      id: '/clases'
      path: '/clases'
      fullPath: '/clases'
      preLoaderRoute: typeof ClasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/control': {
      id: '/control'
      path: '/control'
      fullPath: '/control'
      preLoaderRoute: typeof ControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mesas': {
      id: '/mesas'
      path: '/mesas'
      fullPath: '/mesas'
      preLoaderRoute: typeof MesasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mural': {
      id: '/mural'
      path: '/mural'
      fullPath: '/mural'
      preLoaderRoute: typeof MuralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rutas': {
      id: '/rutas'
      path: '/rutas'
      fullPath: '/rutas'
      preLoaderRoute: typeof RutasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios': {
      id: '/servicios'
      path: '/servicios'
      fullPath: '/servicios'
      preLoaderRoute: typeof ServiciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media-token': {
      id: '/api/media-token'
      path: '/api/media-token'
      fullPath: '/api/media-token'
      preLoaderRoute: typeof ApiMediaTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  BibliotecaRoute: BibliotecaRoute,
  BitacoraRoute: BitacoraRoute,
  CatedrasRoute: CatedrasRoute,
  ClasesRoute: ClasesRoute,
  ControlRoute: ControlRoute,
  LoginRoute: LoginRoute,
  MesasRoute: MesasRoute,
  MuralRoute: MuralRoute,
  RegistroRoute: RegistroRoute,
  RutasRoute: RutasRoute,
  ServiciosRoute: ServiciosRoute,
  ApiMediaTokenRoute: ApiMediaTokenRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
